(function(){'use strict';var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var e=0;return function(){return e<a.length?{done:!1,value:a[e++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,e,c){a!=Array.prototype&&a!=Object.prototype&&(a[e]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.Symbol=function(){var a=0;return function(e){return $jscomp.SYMBOL_PREFIX+(e||"")+a++}}();$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};
$jscomp.makeIterator=function(a){var e="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return e?e.call(a):$jscomp.arrayIterator(a)};$jscomp.polyfill=function(a,e,c,b){if(e){c=$jscomp.global;a=a.split(".");for(b=0;b<a.length-1;b++){var f=a[b];f in c||(c[f]={});c=c[f]}a=a[a.length-1];b=c[a];e=e(b);e!=b&&null!=e&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:e})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function e(){this.batch_=null}function c(h){return h instanceof f?h:new f(function(a,b){a(h)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;e.prototype.asyncExecute=function(h){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(h);return this};e.prototype.asyncExecuteBatch_=function(){var h=this;this.asyncExecuteFunction(function(){h.executeBatch_()})};var b=$jscomp.global.setTimeout;e.prototype.asyncExecuteFunction=function(h){b(h,
0)};e.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var h=this.batch_;this.batch_=[];for(var a=0;a<h.length;++a){var b=h[a];h[a]=null;try{b()}catch(v){this.asyncThrow_(v)}}}this.batch_=null};e.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var f=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var h=this.createResolveAndReject_();try{a(h.resolve,h.reject)}catch(w){h.reject(w)}};f.prototype.createResolveAndReject_=
function(){function a(a){return function(h){f||(f=!0,a.call(b,h))}}var b=this,f=!1;return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};f.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof f)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};f.prototype.resolveToNonPromiseObj_=function(a){var b=
void 0;try{b=a.then}catch(w){this.reject_(w);return}"function"==typeof b?this.settleSameAsThenable_(b,a):this.fulfill_(a)};f.prototype.reject_=function(a){this.settle_(2,a)};f.prototype.fulfill_=function(a){this.settle_(1,a)};f.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};f.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=
0;a<this.onSettledCallbacks_.length;++a)k.asyncExecute(this.onSettledCallbacks_[a]);this.onSettledCallbacks_=null}};var k=new e;f.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};f.prototype.settleSameAsThenable_=function(a,b){var f=this.createResolveAndReject_();try{a.call(b,f.resolve,f.reject)}catch(v){f.reject(v)}};f.prototype.then=function(a,b){function e(a,b){return"function"==typeof a?function(b){try{h(a(b))}catch(u){c(u)}}:
b}var h,c,k=new f(function(a,b){h=a;c=b});this.callWhenSettled_(e(a,h),e(b,c));return k};f.prototype.catch=function(a){return this.then(void 0,a)};f.prototype.callWhenSettled_=function(a,b){function f(){switch(e.state_){case 1:a(e.result_);break;case 2:b(e.result_);break;default:throw Error("Unexpected state: "+e.state_);}}var e=this;null==this.onSettledCallbacks_?k.asyncExecute(f):this.onSettledCallbacks_.push(f)};f.resolve=c;f.reject=function(a){return new f(function(b,f){f(a)})};f.race=function(a){return new f(function(b,
f){for(var e=$jscomp.makeIterator(a),h=e.next();!h.done;h=e.next())c(h.value).callWhenSettled_(b,f)})};f.all=function(a){var b=$jscomp.makeIterator(a),e=b.next();return e.done?c([]):new f(function(a,f){function h(b){return function(f){k[b]=f;q--;0==q&&a(k)}}var k=[],q=0;do k.push(void 0),q++,c(e.value).callWhenSettled_(h(k.length-1),f),e=b.next();while(!e.done)})};return f},"es6","es3");
(function(a){function e(b){if(c[b])return c[b].exports;var f=c[b]={i:b,l:!1,exports:{}};a[b].call(f.exports,f,f.exports,e);f.l=!0;return f.exports}var c={};e.m=a;e.c=c;e.d=function(a,f,c){e.o(a,f)||Object.defineProperty(a,f,{enumerable:!0,get:c})};e.r=function(a){$jscomp.initSymbol();$jscomp.initSymbol();"undefined"!==typeof Symbol&&Symbol.toStringTag&&($jscomp.initSymbol(),Object.defineProperty(a,Symbol.toStringTag,{value:"Module"}));Object.defineProperty(a,"__esModule",{value:!0})};e.t=function(a,
f){f&1&&(a=e(a));if(f&8||f&4&&"object"===typeof a&&a&&a.__esModule)return a;var b=Object.create(null);e.r(b);Object.defineProperty(b,"default",{enumerable:!0,value:a});if(f&2&&"string"!=typeof a)for(var h in a)e.d(b,h,function(b){return a[b]}.bind(null,h));return b};e.n=function(a){var b=a&&a.__esModule?function(){return a["default"]}:function(){return a};e.d(b,"a",b);return b};e.o=function(a,f){return Object.prototype.hasOwnProperty.call(a,f)};e.p="/core/office/";return e(e.s=8)})([function(a,e,
c){c.d(e,"a",function(){return k});a="undefined"===typeof window?self:window;var b=a._trnDebugMode||a._trnLogMode,f=a._logFiltersEnabled?a._logFiltersEnabled:{},k=function(a,e){e||(e=a,a="default");b&&f[a]&&console.log(a+": "+e)}},function(a,e,c){c.d(e,"a",function(){return u});c.d(e,"b",function(){return C});var b=c(0),f=c(6),k="undefined"===typeof window?self:window,h=k.importScripts,x=function(a){if("string"===typeof a){for(var g=new Uint8Array(a.length),d=a.length,b=0;b<d;b++)g[b]=a.charCodeAt(b);
return g}return a},w=function(a){if("string"!==typeof a){for(var g="",d=0,b=a.length,f;d<b;)f=a.subarray(d,d+1024),d+=1024,g+=String.fromCharCode.apply(null,f);return g}return a},v=!1,y=function(a,d){v||(h(k.basePath+"decode.min.js"),v=!0);a=self.BrotliDecode(x(a));return d?a:w(a)},t=!1,r=function(a,d){t||(h(k.basePath+"rawinflate.js",k.basePath+"pako_inflate.min.js"),t=!0);var g=10;if("string"===typeof a){if(a.charCodeAt(3)&8){for(;0!==a.charCodeAt(g);++g);++g}}else if(a[3]&8){for(;0!==a[g];++g);
++g}if(d)return a=x(a),a=a.subarray(g,a.length-8),k.pako.inflate(a,{windowBits:-15});a=w(a);a=a.substring(g,a.length-8);return f.a.inflate(a)},q=function(a,d){return d?a:w(a)},l=function(a){var d=!a.shouldOutputArray,g=new XMLHttpRequest;g.open("GET",a.url,a.isAsync);var f=d&&g.overrideMimeType;g.responseType=f?"text":"arraybuffer";f&&g.overrideMimeType("text/plain; charset=x-user-defined");g.send();var e=function(){var e=Date.now();var z=f?g.responseText:new Uint8Array(g.response);Object(b.a)("worker",
"Result length is "+z.length);z.length<a.compressedMaximum?(z=a.decompressFunction(z,a.shouldOutputArray),Object(b.a)("worker","Decompressed length is "+z.length),console.warn("There may be some degradation of performance. Your server has not been configured to serve .gz. and .br. files with the expected Content-Encoding. See http://www.pdftron.com/kb_content_encoding for instructions on how to resolve this.")):d&&(z=w(z));Object(b.a)("worker",a.url+" Decompression took "+(Date.now()-e));return z};
if(a.isAsync)var n=new Promise(function(d,b){g.onload=function(){200===this.status?d(e()):b("Download Failed "+a.url)};g.onerror=function(){b("Network error occurred "+a.url)}});else{if(200===g.status)return e();throw Error("Failed to load "+a.url);}return n},u=function(a){var d=a.lastIndexOf("/");-1===d&&(d=0);var b=a.slice(d).replace(".",".br.");return a.slice(0,d)+b},d=function(a,d){var b=a.lastIndexOf("/");-1===b&&(b=0);var g=a.slice(b).replace(".",".gz.");d.url=a.slice(0,b)+g;d.decompressFunction=
r;return l(d)},n=function(a,d){d.url=u(a);d.decompressFunction=y;return l(d)},p=function(a,d){d.url=a;d.decompressFunction=q;return l(d)},D=function(a,d,b,f){return a.catch(function(a){console.warn(a);return f(d,b)})},C=function(a,b,f,e){var g={};g.compressedMaximum=b;g.isAsync=f;g.shouldOutputArray=e;a:if(b=[n,d,p],g.isAsync){var m=b[0](a,g);for(f=1;f<b.length;++f)m=D(m,a,g,b[f])}else{for(f=0;f<b.length;++f)try{m=b[f](a,g);break a}catch(G){console.warn(G.message)}throw Error("");}return m}},function(a,
e,c){c.d(e,"c",function(){return h});c.d(e,"b",function(){return x});c.d(e,"a",function(){return w});var b="undefined"===typeof window?self:window;a=function(){var a=navigator.userAgent.toLowerCase();return(a=/(msie) ([\w.]+)/.exec(a)||/(trident)(?:.*? rv:([\w.]+)|)/.exec(a))?parseInt(a[2],10):a}();(function(){var a=b.navigator.userAgent.match(/Chrome\/(.*?) /);return a?parseInt(a[1],10):a})();(function(){var a=b.navigator.userAgent.match(/OPR/),f=b.navigator.userAgent.match(/Maxthon/),e=b.navigator.userAgent.match(/Edge/);
return b.navigator.userAgent.match(/Chrome\/(.*?) /)&&!a&&!f&&!e})();navigator.userAgent.match(/Edge/i);var f=/^((?!chrome|android).)*safari/i.test(b.navigator.userAgent);b.navigator.userAgent.match(/(iPad|iPhone|iPod)/i);b.navigator.userAgent.match(/Firefox/);!a&&(navigator.userAgent.match(/Android/i)||navigator.userAgent.match(/webOS/i)||navigator.userAgent.match(/iPhone/i)||navigator.userAgent.match(/iPod/i)||navigator.userAgent.match(/iPad/i)||navigator.userAgent.match(/Touch/i)||navigator.userAgent.match(/IEMobile/i)||
navigator.userAgent.match(/Silk/i));navigator.userAgent.match(/(iPad|iPhone|iPod)/i);b.navigator.userAgent.indexOf("Android");var k=/Mac OS X 10_13_6.*\(KHTML, like Gecko\)$/.test(b.navigator.userAgent),h=function(){return f||k},x=!(!self.WebAssembly||!self.WebAssembly.validate),w=-1<b.navigator.userAgent.indexOf("Edge/16")||-1<b.navigator.userAgent.indexOf("MSAppHost")},function(a,e){e=function(){return this}();try{e=e||(new Function("return this"))()}catch(c){"object"===typeof window&&(e=window)}a.exports=
e},function(a,e,c){c.d(e,"a",function(){return w});var b=c(5),f=c(1),k=c(7),h=c(2);a="undefined"===typeof window?self:window;a.Uint8ClampedArray||(a.Uint8ClampedArray=a.Uint8Array);"undefined"===typeof a.crypto&&(a.crypto={getRandomValues:function(a){for(var b=0;b<a.length;b++)a[b]=256*Math.random()}});var x=function(a){var b=this;this.promise=a.then(function(a){b.response=a;b.status=200})};x.prototype={addEventListener:function(a,b){this.promise.then(b)}};var w=function(a,e,c){if(!h.b||h.a||Object(h.c)()||
c){c=Object(f.b)((Module.asmjsPrefix?Module.asmjsPrefix:"")+a+".js.mem",e[".js.mem"],!1);var t=Object(f.b)((Module.memoryInitializerPrefixURL?Module.memoryInitializerPrefixURL:"")+a+".mem",e[".mem"],!0,!0);Module.memoryInitializerRequest=new x(t)}else Module.instantiateWasm=function(f,c){return Object(k.a)(Object(b.a)(),a+"Wasm.wasm",f,e["Wasm.wasm"]).then(function(a){c(a)})},c=Object(f.b)(a+"Wasm.js.mem",e["Wasm.js.mem"],!1,!1);eval.call(self,c)}},function(a,e,c){function b(){return f}c.d(e,"a",
function(){return b});var f=21},function(a,e,c){var b=[0,1,3,7,15,31,63,127,255,511,1023,2047,4095,8191,16383,32767,65535],f=[3,4,5,6,7,8,9,10,11,13,15,17,19,23,27,31,35,43,51,59,67,83,99,115,131,163,195,227,258,0,0],k=[0,0,0,0,0,0,0,0,1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5,0,99,99],h=[1,2,3,4,5,7,9,13,17,25,33,49,65,97,129,193,257,385,513,769,1025,1537,2049,3073,4097,6145,8193,12289,16385,24577],x=[0,0,0,0,1,1,2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9,10,10,11,11,12,12,13,13],w=[16,17,18,0,8,7,9,6,10,5,11,
4,12,3,13,2,14,1,15],v=function(){this.list=this.next=null},y=function(){this.n=this.b=this.e=0;this.t=null},t=function(a,b,f,d,e,c){this.BMAX=16;this.N_MAX=288;this.status=0;this.root=null;this.m=0;var n=Array(this.BMAX+1),h,g,m,q=Array(this.BMAX+1),k,p=new y,u=Array(this.BMAX);var l=Array(this.N_MAX);var z=Array(this.BMAX+1),F,x;var t=this.root=null;for(g=0;g<n.length;g++)n[g]=0;for(g=0;g<q.length;g++)q[g]=0;for(g=0;g<u.length;g++)u[g]=null;for(g=0;g<l.length;g++)l[g]=0;for(g=0;g<z.length;g++)z[g]=
0;var w=256<b?a[256]:this.BMAX;var r=a;var B=0;g=b;do n[r[B]]++,B++;while(0<--g);if(n[0]==b)this.root=null,this.status=this.m=0;else{for(m=1;m<=this.BMAX&&0==n[m];m++);var E=m;c<m&&(c=m);for(g=this.BMAX;0!=g&&0==n[g];g--);var J=g;c>g&&(c=g);for(F=1<<m;m<g;m++,F<<=1)if(0>(F-=n[m])){this.status=2;this.m=c;return}if(0>(F-=n[g]))this.status=2,this.m=c;else{n[g]+=F;z[1]=m=0;r=n;B=1;for(k=2;0<--g;)z[k++]=m+=r[B++];r=a;g=B=0;do 0!=(m=r[B++])&&(l[z[m]++]=g);while(++g<b);b=z[J];z[0]=g=0;r=l;B=0;l=-1;var A=
q[0]=0;k=null;for(x=0;E<=J;E++)for(a=n[E];0<a--;){for(;E>A+q[1+l];){A+=q[1+l];l++;x=(x=J-A)>c?c:x;if((h=1<<(m=E-A))>a+1)for(h-=a+1,k=E;++m<x&&!((h<<=1)<=n[++k]);)h-=n[k];A+m>w&&A<w&&(m=w-A);x=1<<m;q[1+l]=m;k=Array(x);for(h=0;h<x;h++)k[h]=new y;t=null==t?this.root=new v:t.next=new v;t.next=null;t.list=k;u[l]=k;0<l&&(z[l]=g,p.b=q[l],p.e=16+m,p.t=k,m=(g&(1<<A)-1)>>A-q[l],u[l-1][m].e=p.e,u[l-1][m].b=p.b,u[l-1][m].n=p.n,u[l-1][m].t=p.t)}p.b=E-A;B>=b?p.e=99:r[B]<f?(p.e=256>r[B]?16:15,p.n=r[B++]):(p.e=e[r[B]-
f],p.n=d[r[B++]-f]);h=1<<E-A;for(m=g>>A;m<x;m+=h)k[m].e=p.e,k[m].b=p.b,k[m].n=p.n,k[m].t=p.t;for(m=1<<E-1;0!=(g&m);m>>=1)g^=m;for(g^=m;(g&(1<<A)-1)!=z[l];)A-=q[l],l--}this.m=q[1];this.status=0!=F&&1!=J?1:0}}},r={Stream:function(a){this.zip_inflate_start();this.zip_inflate_data=a;this.zip_inflate_pos=0}};r.Stream.prototype={getBytes:function(a){for(var b,f=Array(1024),d=[],e=0;e<a&&0<(b=this.zip_inflate_internal(f,0,f.length));)d[d.length]=String.fromCharCode.apply(null,f.slice(0,b)),e+=b;return e?
(this.zip_inflate_data=this.zip_inflate_data.slice(this.zip_inflate_pos),this.zip_inflate_pos=0,d.join("")):""},zip_GET_BYTE:function(){return this.zip_inflate_data.length==this.zip_inflate_pos?-1:this.zip_inflate_data.charCodeAt(this.zip_inflate_pos++)&255},zip_NEEDBITS:function(a){for(;this.zip_bit_len<a;)this.zip_bit_buf|=this.zip_GET_BYTE()<<this.zip_bit_len,this.zip_bit_len+=8},zip_GETBITS:function(a){return this.zip_bit_buf&b[a]},zip_DUMPBITS:function(a){this.zip_bit_buf>>=a;this.zip_bit_len-=
a},zip_inflate_codes:function(a,b,f){var d,e;if(0==f)return 0;for(e=0;;){this.zip_NEEDBITS(this.zip_bl);var c=this.zip_tl.list[this.zip_GETBITS(this.zip_bl)];for(d=c.e;16<d;){if(99==d)return-1;this.zip_DUMPBITS(c.b);d-=16;this.zip_NEEDBITS(d);c=c.t[this.zip_GETBITS(d)];d=c.e}this.zip_DUMPBITS(c.b);if(16==d)this.zip_wp&=32767,a[b+e++]=this.zip_slide[this.zip_wp++]=c.n;else{if(15==d)break;this.zip_NEEDBITS(d);this.zip_copy_leng=c.n+this.zip_GETBITS(d);this.zip_DUMPBITS(d);this.zip_NEEDBITS(this.zip_bd);
c=this.zip_td.list[this.zip_GETBITS(this.zip_bd)];for(d=c.e;16<d;){if(99==d)return-1;this.zip_DUMPBITS(c.b);d-=16;this.zip_NEEDBITS(d);c=c.t[this.zip_GETBITS(d)];d=c.e}this.zip_DUMPBITS(c.b);this.zip_NEEDBITS(d);this.zip_copy_dist=this.zip_wp-c.n-this.zip_GETBITS(d);for(this.zip_DUMPBITS(d);0<this.zip_copy_leng&&e<f;)this.zip_copy_leng--,this.zip_copy_dist&=32767,this.zip_wp&=32767,a[b+e++]=this.zip_slide[this.zip_wp++]=this.zip_slide[this.zip_copy_dist++]}if(e==f)return f}this.zip_method=-1;return e},
zip_inflate_stored:function(a,b,f){var d=this.zip_bit_len&7;this.zip_DUMPBITS(d);this.zip_NEEDBITS(16);d=this.zip_GETBITS(16);this.zip_DUMPBITS(16);this.zip_NEEDBITS(16);if(d!=(~this.zip_bit_buf&65535))return-1;this.zip_DUMPBITS(16);this.zip_copy_leng=d;for(d=0;0<this.zip_copy_leng&&d<f;)this.zip_copy_leng--,this.zip_wp&=32767,this.zip_NEEDBITS(8),a[b+d++]=this.zip_slide[this.zip_wp++]=this.zip_GETBITS(8),this.zip_DUMPBITS(8);0==this.zip_copy_leng&&(this.zip_method=-1);return d},zip_inflate_fixed:function(a,
b,e){if(null==this.zip_fixed_tl){var d,c=Array(288);for(d=0;144>d;d++)c[d]=8;for(;256>d;d++)c[d]=9;for(;280>d;d++)c[d]=7;for(;288>d;d++)c[d]=8;this.zip_fixed_bl=7;d=new t(c,288,257,f,k,this.zip_fixed_bl);if(0!=d.status)return alert("HufBuild error: "+d.status),-1;this.zip_fixed_tl=d.root;this.zip_fixed_bl=d.m;for(d=0;30>d;d++)c[d]=5;this.zip_fixed_bd=5;d=new t(c,30,0,h,x,this.zip_fixed_bd);if(1<d.status)return this.zip_fixed_tl=null,alert("HufBuild error: "+d.status),-1;this.zip_fixed_td=d.root;this.zip_fixed_bd=
d.m}this.zip_tl=this.zip_fixed_tl;this.zip_td=this.zip_fixed_td;this.zip_bl=this.zip_fixed_bl;this.zip_bd=this.zip_fixed_bd;return this.zip_inflate_codes(a,b,e)},zip_inflate_dynamic:function(a,b,e){var d,c,p,l=Array(316);for(d=0;d<l.length;d++)l[d]=0;this.zip_NEEDBITS(5);var q=257+this.zip_GETBITS(5);this.zip_DUMPBITS(5);this.zip_NEEDBITS(5);var g=1+this.zip_GETBITS(5);this.zip_DUMPBITS(5);this.zip_NEEDBITS(4);d=4+this.zip_GETBITS(4);this.zip_DUMPBITS(4);if(286<q||30<g)return-1;for(c=0;c<d;c++)this.zip_NEEDBITS(3),
l[w[c]]=this.zip_GETBITS(3),this.zip_DUMPBITS(3);for(;19>c;c++)l[w[c]]=0;this.zip_bl=7;c=new t(l,19,19,null,null,this.zip_bl);if(0!=c.status)return-1;this.zip_tl=c.root;this.zip_bl=c.m;var m=q+g;for(d=p=0;d<m;){this.zip_NEEDBITS(this.zip_bl);var u=this.zip_tl.list[this.zip_GETBITS(this.zip_bl)];c=u.b;this.zip_DUMPBITS(c);c=u.n;if(16>c)l[d++]=p=c;else if(16==c){this.zip_NEEDBITS(2);c=3+this.zip_GETBITS(2);this.zip_DUMPBITS(2);if(d+c>m)return-1;for(;0<c--;)l[d++]=p}else{17==c?(this.zip_NEEDBITS(3),
c=3+this.zip_GETBITS(3),this.zip_DUMPBITS(3)):(this.zip_NEEDBITS(7),c=11+this.zip_GETBITS(7),this.zip_DUMPBITS(7));if(d+c>m)return-1;for(;0<c--;)l[d++]=0;p=0}}this.zip_bl=9;c=new t(l,q,257,f,k,this.zip_bl);0==this.zip_bl&&(c.status=1);if(0!=c.status)return-1;this.zip_tl=c.root;this.zip_bl=c.m;for(d=0;d<g;d++)l[d]=l[d+q];this.zip_bd=6;c=new t(l,g,0,h,x,this.zip_bd);this.zip_td=c.root;this.zip_bd=c.m;return 0==this.zip_bd&&257<q||0!=c.status?-1:this.zip_inflate_codes(a,b,e)},zip_inflate_start:function(){null==
this.zip_slide&&(this.zip_slide=Array(65536));this.zip_bit_len=this.zip_bit_buf=this.zip_wp=0;this.zip_method=-1;this.zip_eof=!1;this.zip_copy_leng=this.zip_copy_dist=0;this.zip_fixed_tl=this.zip_tl=null},zip_inflate_internal:function(a,b,c){var d;for(d=0;d<c&&(!this.zip_eof||-1!=this.zip_method);){if(0<this.zip_copy_leng){if(0!=this.zip_method)for(;0<this.zip_copy_leng&&d<c;)this.zip_copy_leng--,this.zip_copy_dist&=32767,this.zip_wp&=32767,a[b+d++]=this.zip_slide[this.zip_wp++]=this.zip_slide[this.zip_copy_dist++];
else{for(;0<this.zip_copy_leng&&d<c;)this.zip_copy_leng--,this.zip_wp&=32767,this.zip_NEEDBITS(8),a[b+d++]=this.zip_slide[this.zip_wp++]=this.zip_GETBITS(8),this.zip_DUMPBITS(8);0==this.zip_copy_leng&&(this.zip_method=-1)}if(d==c)break}if(-1==this.zip_method){if(this.zip_eof)break;this.zip_NEEDBITS(1);0!=this.zip_GETBITS(1)&&(this.zip_eof=!0);this.zip_DUMPBITS(1);this.zip_NEEDBITS(2);this.zip_method=this.zip_GETBITS(2);this.zip_DUMPBITS(2);this.zip_tl=null;this.zip_copy_leng=0}switch(this.zip_method){case 0:var f=
this.zip_inflate_stored(a,b+d,c-d);break;case 1:f=null!=this.zip_tl?this.zip_inflate_codes(a,b+d,c-d):this.zip_inflate_fixed(a,b+d,c-d);break;case 2:f=null!=this.zip_tl?this.zip_inflate_codes(a,b+d,c-d):this.zip_inflate_dynamic(a,b+d,c-d);break;default:f=-1}if(-1==f)return this.zip_eof?0:-1;d+=f}return d}};r.inflate=function(a){return(new r.Stream(a)).getBytes(4E9)};e.a=r},function(a,e,c){function b(a){return new Promise(function(b,c){var f=indexedDB.open(w,a);f.onerror=c.bind(null,"Error opening wasm cache database");
f.onsuccess=function(){b(f.result)};f.onupgradeneeded=function(a){var b=f.result;b.objectStoreNames.contains(v)&&(console.log("Clearing out version "+a.oldVersion+" wasm cache"),b.deleteObjectStore(v));console.log("Creating version "+a.newVersion+" wasm cache");b.createObjectStore(v)}})}function f(a,b){return new Promise(function(c,f){var e=a.transaction([v]).objectStore(v).get(b);e.onsuccess=function(a){e.result?c(e.result):f("Module "+b+" was not found in wasm cache")};e.onerror=f.bind(null,"Error getting wasm module "+
b)})}function k(a,c,e,k){function l(a,b){a=a.transaction([v],"readwrite").objectStore(v).put(b,c);a.onerror=function(a){console.log("Failed to store in wasm cache: "+a)};a.onsuccess=function(a){console.log("Successfully stored "+c+" in wasm cache")}}function w(a){n=n||Date.now();return a?(Object(h.a)("load","Try instantiateStreaming"),fetch(Object(x.a)(c)).then(function(a){return WebAssembly.instantiateStreaming(a,e)}).catch(function(a){Object(h.a)("load","instantiateStreaming Failed "+c+" message "+
a.message);return w(!1)})):Object(x.b)(c,k,!0,!0).then(function(a){d=Date.now();Object(h.a)("load","Request took "+(d-n)+" ms");return WebAssembly.instantiate(a,e)})}var d,n;return b(a).then(function(a){return f(a,c).then(function(a){Object(h.a)("Found "+c+" in wasm cache");return WebAssembly.instantiate(a,e)},function(b){Object(h.a)(b);return w(!!WebAssembly.instantiateStreaming).then(function(b){try{Object(h.a)("load","WASM compilation took "+(Date.now()-(d||n))+" ms"),l(a,b.module)}catch(g){}return b.instance})})},
function(a){console.log(a);return w().then(function(a){return a.instance})})}c.d(e,"a",function(){return k});var h=c(0),x=c(1),w="wasm-cache",v="wasm-cache"},function(a,e,c){a.exports=c(9)},function(a,e,c){c.r(e);c(10);c(15);c(16)},function(a,e,c){(function(a,f){(function(b){function f(){for(var a=0;a<H.length;a++)H[a][0](H[a][1]);H=[];G=!1}function e(a,b){H.push([a,b]);G||(G=!0,M(f,0))}function k(a,b){function d(a){t(b,a)}function c(a){q(b,a)}try{a(d,c)}catch(I){c(I)}}function v(a){var b=a.owner,
d=b.state_;b=b.data_;var c=a[d];a=a.then;if("function"===typeof c){d=m;try{b=c(b)}catch(I){q(a,I)}}y(a,b)||(d===m&&t(a,b),d===K&&q(a,b))}function y(a,b){var d;try{if(a===b)throw new TypeError("A promises callback cannot return that same promise.");if(b&&("function"===typeof b||"object"===typeof b)){var c=b.then;if("function"===typeof c)return c.call(b,function(c){d||(d=!0,b!==c?t(a,c):r(a,c))},function(b){d||(d=!0,q(a,b))}),!0}}catch(I){return d||q(a,I),!0}return!1}function t(a,b){a!==b&&y(a,b)||
r(a,b)}function r(a,b){a.state_===C&&(a.state_=g,a.data_=b,e(u,a))}function q(a,b){a.state_===C&&(a.state_=g,a.data_=b,e(d,a))}function l(a){var b=a.then_;a.then_=void 0;for(a=0;a<b.length;a++)v(b[a])}function u(a){a.state_=m;l(a)}function d(a){a.state_=K;l(a)}function n(a){if("function"!==typeof a)throw new TypeError("Promise constructor takes a function argument");if(!1===this instanceof n)throw new TypeError("Failed to construct 'Promise': Please use the 'new' operator, this object constructor cannot be called as a function.");
this.then_=[];k(a,this)}b.createPromiseCapability=function(){var a={},b=new n(function(b,d){a.resolve=b;a.reject=d});a.promise=b;return a};var p=b.Promise,D=p&&"resolve"in p&&"reject"in p&&"all"in p&&"race"in p&&function(){var a;new p(function(b){a=b});return"function"===typeof a}();"undefined"!==typeof exports&&exports?(exports.Promise=D?p:n,exports.Polyfill=n):"function"===typeof define&&c(14)?define(function(){return D?p:n}):D||(b.Promise=n);var C="pending",g="sealed",m="fulfilled",K="rejected",
L=function(){},M="undefined"!==typeof a?a:setTimeout,H=[],G;n.prototype={constructor:n,state_:C,then_:null,data_:void 0,then:function(a,b){a={owner:this,then:new this.constructor(L),fulfilled:a,rejected:b};this.state_===m||this.state_===K?e(v,a):this.then_.push(a);return a.then},"catch":function(a){return this.then(null,a)}};n.all=function(a){if("[object Array]"!==Object.prototype.toString.call(a))throw new TypeError("You must pass an array to Promise.all().");return new this(function(b,d){function c(a){e++;
return function(d){f[a]=d;--e||b(f)}}for(var f=[],e=0,g=0,h;g<a.length;g++)(h=a[g])&&"function"===typeof h.then?h.then(c(g),d):f[g]=h;e||b(f)})};n.race=function(a){if("[object Array]"!==Object.prototype.toString.call(a))throw new TypeError("You must pass an array to Promise.race().");return new this(function(b,d){for(var c=0,f;c<a.length;c++)(f=a[c])&&"function"===typeof f.then?f.then(b,d):b(f)})};n.resolve=function(a){return a&&"object"===typeof a&&a.constructor===this?a:new this(function(b){b(a)})};
n.reject=function(a){return new this(function(b,d){d(a)})}})("undefined"!==typeof window?window:"undefined"!==typeof f?f:"undefined"!==typeof self?self:void 0)}).call(this,c(11).setImmediate,c(3))},function(a,e,c){(function(a){function b(a,b){this._id=a;this._clearFn=b}var k="undefined"!==typeof a&&a||"undefined"!==typeof self&&self||window,h=Function.prototype.apply;e.setTimeout=function(){return new b(h.call(setTimeout,k,arguments),clearTimeout)};e.setInterval=function(){return new b(h.call(setInterval,
k,arguments),clearInterval)};e.clearTimeout=e.clearInterval=function(a){a&&a.close()};b.prototype.unref=b.prototype.ref=function(){};b.prototype.close=function(){this._clearFn.call(k,this._id)};e.enroll=function(a,b){clearTimeout(a._idleTimeoutId);a._idleTimeout=b};e.unenroll=function(a){clearTimeout(a._idleTimeoutId);a._idleTimeout=-1};e._unrefActive=e.active=function(a){clearTimeout(a._idleTimeoutId);var b=a._idleTimeout;0<=b&&(a._idleTimeoutId=setTimeout(function(){a._onTimeout&&a._onTimeout()},
b))};c(12);e.setImmediate="undefined"!==typeof self&&self.setImmediate||"undefined"!==typeof a&&a.setImmediate||this&&this.setImmediate;e.clearImmediate="undefined"!==typeof self&&self.clearImmediate||"undefined"!==typeof a&&a.clearImmediate||this&&this.clearImmediate}).call(this,c(3))},function(a,e,c){(function(a,c){(function(a,b){function f(a){delete d[a]}function e(a){if(n)setTimeout(e,0,a);else{var c=d[a];if(c){n=!0;try{var g=c.callback,h=c.args;switch(h.length){case 0:g();break;case 1:g(h[0]);
break;case 2:g(h[0],h[1]);break;case 3:g(h[0],h[1],h[2]);break;default:g.apply(b,h)}}finally{f(a),n=!1}}}}function h(){D=function(a){c.nextTick(function(){e(a)})}}function k(){if(a.postMessage&&!a.importScripts){var b=!0,d=a.onmessage;a.onmessage=function(){b=!1};a.postMessage("","*");a.onmessage=d;return b}}function t(){var b="setImmediate$"+Math.random()+"$",d=function(d){d.source===a&&"string"===typeof d.data&&0===d.data.indexOf(b)&&e(+d.data.slice(b.length))};a.addEventListener?a.addEventListener("message",
d,!1):a.attachEvent("onmessage",d);D=function(d){a.postMessage(b+d,"*")}}function r(){var a=new MessageChannel;a.port1.onmessage=function(a){e(a.data)};D=function(b){a.port2.postMessage(b)}}function q(){var a=p.documentElement;D=function(b){var d=p.createElement("script");d.onreadystatechange=function(){e(b);d.onreadystatechange=null;a.removeChild(d);d=null};a.appendChild(d)}}function l(){D=function(a){setTimeout(e,0,a)}}if(!a.setImmediate){var u=1,d={},n=!1,p=a.document,D,C=Object.getPrototypeOf&&
Object.getPrototypeOf(a);C=C&&C.setTimeout?C:a;"[object process]"==={}.toString.call(a.process)?h():k()?t():a.MessageChannel?r():p&&"onreadystatechange"in p.createElement("script")?q():l();C.setImmediate=function(a){"function"!==typeof a&&(a=new Function(""+a));for(var b=Array(arguments.length-1),c=0;c<b.length;c++)b[c]=arguments[c+1];d[u]={callback:a,args:b};D(u);return u++};C.clearImmediate=f}})("undefined"===typeof self?"undefined"===typeof a?this:a:self)}).call(this,c(3),c(13))},function(a,e){function c(){throw Error("setTimeout has not been defined");
}function b(){throw Error("clearTimeout has not been defined");}function f(a){if(y===setTimeout)return setTimeout(a,0);if((y===c||!y)&&setTimeout)return y=setTimeout,setTimeout(a,0);try{return y(a,0)}catch(n){try{return y.call(null,a,0)}catch(p){return y.call(this,a,0)}}}function k(a){if(t===clearTimeout)return clearTimeout(a);if((t===b||!t)&&clearTimeout)return t=clearTimeout,clearTimeout(a);try{return t(a)}catch(n){try{return t.call(null,a)}catch(p){return t.call(this,a)}}}function h(){q&&l&&(q=
!1,l.length?r=l.concat(r):u=-1,r.length&&x())}function x(){if(!q){var a=f(h);q=!0;for(var b=r.length;b;){l=r;for(r=[];++u<b;)l&&l[u].run();u=-1;b=r.length}l=null;q=!1;k(a)}}function w(a,b){this.fun=a;this.array=b}function v(){}a=a.exports={};try{var y="function"===typeof setTimeout?setTimeout:c}catch(d){y=c}try{var t="function"===typeof clearTimeout?clearTimeout:b}catch(d){t=b}var r=[],q=!1,l,u=-1;a.nextTick=function(a){var b=Array(arguments.length-1);if(1<arguments.length)for(var d=1;d<arguments.length;d++)b[d-
1]=arguments[d];r.push(new w(a,b));1!==r.length||q||f(x)};w.prototype.run=function(){this.fun.apply(null,this.array)};a.title="browser";a.browser=!0;a.env={};a.argv=[];a.version="";a.versions={};a.on=v;a.addListener=v;a.once=v;a.off=v;a.removeListener=v;a.removeAllListeners=v;a.emit=v;a.prependListener=v;a.prependOnceListener=v;a.listeners=function(a){return[]};a.binding=function(a){throw Error("process.binding is not supported");};a.cwd=function(){return"/"};a.chdir=function(a){throw Error("process.chdir is not supported");
};a.umask=function(){return 0}},function(a,e){a.exports={}},function(a,e,c){(function(){ArrayBuffer.prototype.slice||(ArrayBuffer.prototype.slice=function(a,c){void 0===a&&(a=0);void 0===c&&(c=this.byteLength);a=Math.floor(a);c=Math.floor(c);0>a&&(a+=this.byteLength);0>c&&(c+=this.byteLength);a=Math.min(Math.max(0,a),this.byteLength);c=Math.min(Math.max(0,c),this.byteLength);if(0>=c-a)return new ArrayBuffer(0);var b=new ArrayBuffer(c-a),e=new Uint8Array(b);a=new Uint8Array(this,a,c-a);e.set(a);return b})})(self)},
function(a,e,c){var b=c(0),f=c(4),k=null;(function(a){function c(){y=function(){}}function e(a){var b=[];return{resource_array:b,msg:JSON.stringify(a.data,function(a,c){if("object"===typeof c&&(a=null,c instanceof Uint8Array?a=c:c instanceof ArrayBuffer&&(a=new Uint8Array(c)),a)){c=r(a.length);var d=q(c);d&&(new Uint8Array(Module.HEAPU8.buffer,d,a.length)).set(a);b.push(c);return{__trn_res_id:c}}return c})}}function h(a){a=e(a);t(a.msg)}var y,t,r,q;a.basePath="../";var l=a.officeWorkerPath||"";a.workerBasePath&&
(a.basePath=a.workerBasePath);var u=function(a){var b={};decodeURIComponent(a.slice(1)).split("&").forEach(function(a){a=a.split("=",2);b[a[0]]=a[1]});return b}(a.location.search);a.basePath=u.externalPath?u.externalPath:a.basePath+"external/";importScripts(a.basePath+"Promise.js");var d=[];onmessage=function(a){d||(d=[]);d.push(a)};a.ContinueFunc=function(a){y("ContinueFunc called");setTimeout(function(){onmessage({data:{action:"continue"}})},a)};if(u.pdfWorkerPath)var n=u.pdfWorkerPath;if(u.officeAsmPath)var p=
u.officeAsmPath;a.Module={memoryInitializerPrefixURL:n,asmjsPrefix:p,onRuntimeInitialized:function(){console.log("on ready");y||c();var a=Date.now()-k;Object(b.a)("load","time duration from start to ready: "+JSON.stringify(a));t=Module.cwrap("TRN_OnMessage",null,["string"]);r=Module.cwrap("TRN_CreateBufferResource","number",["number"]);q=Module.cwrap("TRN_GetResourcePointer","number",["number"]);y("OnReady called");onmessage=h;Module._TRN_InitWorker();for(a=0;a<d.length;++a)onmessage(d[a]);d=null},
fetchSelf:function(){k=Date.now();Object(f.a)(l+"WebOfficeWorker",{"Wasm.wasm":5E6,"Wasm.js.mem":1E5,".js.mem":5E6,".mem":3E6},!!navigator.userAgent.match(/Edge/i));console.log("end of fetch self")},noExitRuntime:!0};a.Module.fetchSelf()})("undefined"===typeof window?self:window)}]);}).call(this || window)
