version: 2.1
orbs:
  # "cypress-io/cypress@1" installs the latest published
  # version "1.x.y" of the orb. We recommend you then use
  # the strict explicit version "cypress-io/cypress@1.x.y"
  # to lock the version and prevent unexpected CI changes
  cypress: cypress-io/cypress@1
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Lint
          command: npm run lint
      # - run:
      #     name: Spin up server for e2e
      #     command: npm start
      # - run:
      #     name: Run e2e tests
      #     command: npm run cy:run
      # - run:
      #     name: Generate minified bundle
      #     command: npm run build
      # - cypress/run
workflows: 
  test_and_deploy:
    jobs:
      # - build
      # - cypress/install:
      #     build: 'npm run build'
      - cypress/install
      - cypress/run:
          requires:
            - cypress/install
          start: npm start
          wait-on: 'http://localhost:3000/#d=https://pdftron.s3.amazonaws.com/downloads/pl/demo-annotated.pdf&a=1'
          command: npm run cy:run
          no-workspace: true
          # browser: chrome
          executor: cypress/browsers-chrome69