version: 2.1
orbs:
  # "cypress-io/cypress@1" installs the latest published
  # version "1.x.y" of the orb. We recommend you then use
  # the strict explicit version "cypress-io/cypress@1.x.y"
  # to lock the version and prevent unexpected CI changes
  cypress: cypress-io/cypress@1
executors:
  with-chrome:
    docker:
      - image: 'cypress/base:12.4.0'
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run:
        # https://gist.github.com/phra/192b6c0ada3f6eaf4029e430430b79fe
          name: install Chrome
          command:  |
            sudo apt-get update
            sudo apt-get install lsb-release libappindicator3-1
            curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i google-chrome.deb
            sudo sed -i 's|HERE/chrome"|HERE/chrome" --no-sandbox|g' /opt/google/chrome/google-chrome
            rm google-chrome.deb
      # - run:
      #     name: Install dependencies
      #     command: npm install
      # - run:
      #     name: Lint
      #     command: npm run lint
      # - run:
      #     name: Generate minified bundle
      #     command: npm run build

workflows:
  version: 2
  test_and_deploy:
    jobs:
      # - build
      # - cypress/install:
      #     requires:
      #       - build
      - cypress/install:
          - executor: with-chrome
      - cypress/run:
          requires:
            - cypress/install
          post-steps:
            # TODO make it download webviewer here once the newest version is rdy and published to npm repo
            - store_artifacts:
                path: ./test/cypress/snapshots
          start: npm start
          wait-on: 'http://localhost:3000/#d=https://pdftron.s3.amazonaws.com/downloads/pl/demo-annotated.pdf&a=1'
          command: npm run cy:run
          executor: with-chrome
          # no-workspace: true
          # https://github.com/cypress-io/cypress-docker-images/tree/master/browsers
          # executor: cypress/base:12.4.0
          # browser: chrome