version: 2.1
orbs:
  cypress: cypress-io/cypress@1
executors:
  with-chrome:
    docker:
      # https://github.com/cypress-io/cypress-docker-images/tree/master/browsers
      - image: 'cypress/browsers:node12.4.0-chrome76'
jobs:
  run-lint:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Lint
          command: npm run lint

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - run-lint
      - cypress/run:
          post-steps:
            # TODO make it download webviewer here once the newest version is rdy and published to npm repo
            - store_artifacts:
                path: ./test/cypress/snapshots
          start: npm start
          wait-on: 'http://localhost:3000/#d=https://pdftron.s3.amazonaws.com/downloads/pl/demo-annotated.pdf&a=1'
          command: npm run cy:run
          executor: with-chrome
          no-workspace: true
          # executor: cypress/base:12.4.0
          browser: chrome