export default {
  text: 'ic_annotation_sticky_note_black_24px',
  ink: 'ic_annotation_freehand_black_24px',
  highlight: 'ic_annotation_highlight_black_24px',
  underline: 'ic_annotation_underline_black_24px',
  squiggly: 'ic_annotation_squiggly_black_24px',
  strikeout: 'ic_annotation_strikeout_black_24px',
  freetext: 'ic_annotation_freetext_black_24px',
  callout: 'ic_annotation_callout_black_24px',
  signature: 'ic_annotation_signature_black_24px',
  line: 'ic_annotation_line_black_24px',
  arrow: 'ic_annotation_arrow_black_24px',
  polyline: 'ic_annotation_polyline_black_24px',
  stamp: 'ic_annotation_stamp_black_24px',
  square: 'ic_annotation_square_black_24px',
  circle: 'ic_annotation_circle_black_24px',
  polygon: 'ic_annotation_polygon_black_24px',
  cloud: 'ic_annotation_cloud_black_24px',
};