export default {
  text: 'StrokeColor',
  ink: 'StrokeColor',
  highlight: 'StrokeColor',
  underline: 'StrokeColor',
  squiggly: 'StrokeColor',
  strikeout: 'StrokeColor',
  freetext: 'TextColor',
  callout: 'TextColor',
  signature: 'StrokeColor',
  line: 'StrokeColor',
  arrow: 'StrokeColor',
  polyline: 'StrokeColor',
  stamp: 'StrokeColor',
  square: 'StrokeColor',
  circle: 'StrokeColor',
  polygon: 'StrokeColor',
  cloud: 'StrokeColor',
};