export default {
  Sticky: 'ic_annotation_sticky_note_black_24px',
  'Free Hand': 'ic_annotation_freehand_black_24px',
  Highlight: 'ic_annotation_highlight_black_24px',
  Underline: 'ic_annotation_underline_black_24px',
  Squiggly: 'ic_annotation_squiggly_black_24px',
  Strikeout: 'ic_annotation_strikeout_black_24px',
  FreeText: 'ic_annotation_freetext_black_24px',
  Callout: 'ic_annotation_callout_black_24px',
  Signature: 'ic_annotation_signature_black_24px',
  Line: 'ic_annotation_line_black_24px',
  Arrow: 'ic_annotation_arrow_black_24px',
  Polyline: 'ic_annotation_polyline_black_24px',
  Stamp: 'ic_annotation_stamp_black_24px',
  Rectangle: 'ic_annotation_square_black_24px',
  Ellipse: 'ic_annotation_circle_black_24px',
  Polygon: 'ic_annotation_polygon_black_24px',
  Cloud: 'ic_annotation_cloud_black_24px',
};