export default {
  Sticky: 'StrokeColor',
  'Free Hand': 'StrokeColor',
  Highlight: 'StrokeColor',
  Underline: 'StrokeColor',
  Squiggly: 'StrokeColor',
  Strikeout: 'StrokeColor',
  FreeText: 'TextColor',
  Callout: 'TextColor',
  Signature: 'StrokeColor',
  Line: 'StrokeColor',
  Arrow: 'StrokeColor',
  Polyline: 'StrokeColor',
  Stamp: 'StrokeColor',
  Rectangle: 'StrokeColor',
  Ellipse: 'StrokeColor',
  Polygon: 'StrokeColor',
  Cloud: 'StrokeColor',
};