export default {
  AnnotationEdit: 'selectTool',
  TextSelect: 'selectTool',
  Pan: 'panTool',
  AnnotationCreateSticky: 'stickyTool',
  AnnotationCreateFreeHand: 'freeHandTool',
  AnnotationCreateTextHighlight: 'textHighlightTool',
  AnnotationCreateTextUnderline: 'textUnderlineTool',
  AnnotationCreateTextSquiggly: 'textSquigglyTool',
  AnnotationCreateTextStrikeout: 'textStrikeoutTool',
  AnnotationCreateFreeText: 'freeTextTool',
  AnnotationCreateCallout: 'calloutTool',
  AnnotationCreateSignature: 'signatureTool',
  AnnotationCreateLine: 'lineTool',
  AnnotationCreateArrow: 'arrowTool',
  AnnotationCreatePolyline: 'polylineTool',
  AnnotationCreateStamp: 'stampTool',
  AnnotationCreateRectangle: 'rectangleTool',
  AnnotationCreateEllipse: 'ellipseTool',
  AnnotationCreatePolygon: 'polygonTool',
  AnnotationCreatePolygonCloud: 'polygonCloudTool'
};