import * as eventListeners from 'src/event-listeners';
import hotkeysManager from 'helpers/hotkeysManager';
import core from 'core';
import Events from 'constants/events';

const { ToolNames } = window.Core.Tools;

export default (store, documentViewerKey = 1, skipHotkeys = false) => {
  const { dispatch } = store;
  // TODO Compare: Add event handlers for panels and refactor code for panels
  const onBeforeDocumentLoaded = eventListeners.onBeforeDocumentLoaded(dispatch, documentViewerKey);
  const onCheckStampAnnotationAdded = eventListeners.onCheckStampAnnotationAdded(dispatch, documentViewerKey);
  const onCrossStampAnnotationAdded = eventListeners.onCrossStampAnnotationAdded(dispatch, documentViewerKey);
  const onDisplayModeUpdated = eventListeners.onDisplayModeUpdated(dispatch);
  const onDocumentLoaded = eventListeners.onDocumentLoaded(store, documentViewerKey);
  const enableRedactionElements = eventListeners.enableRedactionElements(dispatch);
  const addPageLabelsToRedux = eventListeners.addPageLabelsToRedux(store, documentViewerKey);
  const handlePasswordModal = eventListeners.handlePasswordModal(dispatch, documentViewerKey);
  const showProgressModal = eventListeners.showProgressModal(dispatch);
  const setPrintHandler = eventListeners.setPrintHandler(store, documentViewerKey);
  const toggleAnnotations = eventListeners.toggleAnnotations();
  const setServerProperties = eventListeners.setServerProperties();
  const checkDocumentForTools = eventListeners.checkDocumentForTools(dispatch);
  const updateOutlines = eventListeners.updateOutlines(dispatch, documentViewerKey);
  const updatePortfolio = eventListeners.updatePortfolio(store, documentViewerKey);
  const configureEditorMode = eventListeners.configureEditorMode(store);
  const setupCompositionInput = eventListeners.setupCompositionInput(documentViewerKey);
  const syncDisplayModeMultiviewer = eventListeners.syncDisplayModeMultiviewer(documentViewerKey);
  const onDocumentUnloaded = eventListeners.onDocumentUnloaded(store, documentViewerKey);
  const onFitModeUpdated = eventListeners.onFitModeUpdated(dispatch);
  const onRotationUpdated = eventListeners.onRotationUpdated(dispatch);
  const onToolUpdated = eventListeners.onToolUpdated(dispatch);
  const onToolModeUpdated = eventListeners.onToolModeUpdated(dispatch, store);
  const onZoomUpdated = eventListeners.onZoomUpdated(dispatch, documentViewerKey, store);
  const onPageNumberUpdated = eventListeners.onPageNumberUpdated(dispatch, documentViewerKey);
  const onUpdateAnnotationPermission = eventListeners.onUpdateAnnotationPermission(store);
  const onAnnotationChanged = eventListeners.onAnnotationChanged(documentViewerKey);
  const onStampAnnotationAdded = eventListeners.onStampAnnotationAdded(dispatch, documentViewerKey);
  const onSignatureAnnotationAdded = eventListeners.onSignatureAnnotationAdded(documentViewerKey, store, dispatch);
  const onStickyAnnotationAdded = eventListeners.onStickyAnnotationAdded(store, documentViewerKey);
  const onCaretAnnotationAdded = eventListeners.onCaretAnnotationAdded(store, documentViewerKey);
  const onFullScreenChange = eventListeners.onFullScreenChange(store);
  const onPagesUpdated = eventListeners.onPagesUpdated(dispatch, documentViewerKey);
  const onLocationSelected = eventListeners.onLocationSelected(store, documentViewerKey);
  const onDotStampAnnotationAdded = eventListeners.onDotStampAnnotationAdded(dispatch, documentViewerKey);
  const onRubberStampAnnotationAdded = eventListeners.onRubberStampAnnotationAdded(documentViewerKey, dispatch, store);
  const onRubberStampsUpdated = eventListeners.onRubberStampsUpdated(dispatch);
  const onReadOnlyModeChanged = eventListeners.onReadOnlyModeChanged(dispatch, store);
  const onPageComplete = eventListeners.onPageComplete(store, documentViewerKey);
  const onFileAttachmentAnnotationAdded = eventListeners.onFileAttachmentAnnotationAdded();
  const onFileAttachmentDataAvailable = eventListeners.onFileAttachmentDataAvailable();
  const onSignatureSaved = eventListeners.onSignatureSaved(dispatch, store);
  const onSignatureDeleted = eventListeners.onSignatureDeleted(dispatch, store);
  const onHistoryChanged = eventListeners.onHistoryChanged(dispatch, documentViewerKey);
  const onFormFieldCreationModeStarted = eventListeners.onFormFieldCreationModeStarted(dispatch, store, hotkeysManager);
  const onFormFieldCreationModeEnded = eventListeners.onFormFieldCreationModeEnded(dispatch, store, hotkeysManager);
  const onImageContentAdded = eventListeners.onImageContentAdded(dispatch, documentViewerKey);
  const onInitialSaved = eventListeners.onInitialSaved(dispatch, store);
  const onInitialDeleted = eventListeners.onInitialDeleted(dispatch, store);
  const onContentEditModeStarted = eventListeners.onContentEditModeStarted(dispatch, store);
  const onContentEditModeEnded = eventListeners.onContentEditModeEnded(dispatch, store);
  const onContentBoxEditStarted = eventListeners.onContentBoxEditStarted(dispatch, hotkeysManager);
  const onContentBoxEditEnded = eventListeners.onContentBoxEditEnded(hotkeysManager);
  const onContentEditDocumentDigitalSigned = eventListeners.onContentEditDocumentDigitalSigned(dispatch);
  const onContentEditPasswordRequired = eventListeners.onContentEditPasswordRequired(dispatch, store);
  const onCompareAnnotationsLoaded = eventListeners.onCompareAnnotationsLoaded(dispatch, store);
  const onAccessibleReadingOrderModeStarted = eventListeners.onAccessibleReadingOrderModeStarted(dispatch, store);
  const onAccessibleReadingOrderModeReady = eventListeners.onAccessibleReadingOrderModeReady(dispatch, store);
  const onAccessibleReadingOrderModeEnded = eventListeners.onAccessibleReadingOrderModeEnded(dispatch, store);
  const onAccessibleReadingOrderModeNoStructure = eventListeners.onAccessibleReadingOrderModeNoStructure(dispatch, store);
  const onUserBookmarksChanged = eventListeners.onUserBookmarksChanged(dispatch, documentViewerKey);
  const onSpreadsheetEditorSelectionChanged = eventListeners.onSpreadsheetEditorSelectionChanged(dispatch);
  const onSpreadsheetEditorEditModeChanged = eventListeners.onSpreadsheetEditorEditModeChanged(dispatch);
  const openSpreadsheetEditorLoadingModal = eventListeners.openSpreadsheetEditorLoadingModal(dispatch);
  const closeSpreadsheetEditorLoadingModal = eventListeners.closeSpreadsheetEditorLoadingModal(dispatch, store);
  const onWidgetHighlightingChanged = eventListeners.onWidgetHighlightingChanged(dispatch, store);
  const onSelectedRangeStyleChanged = eventListeners.onSelectedRangeStyleChanged(dispatch);
  const initializeLayersVisibility = eventListeners.initializeLayersVisibility(store, documentViewerKey);

  return {
    addEventHandlers: () => {
      if (documentViewerKey === 1) {
        // ContentEdit Not supported for MultiViewerMode
        core.addEventListener('contentEditModeStarted', onContentEditModeStarted, undefined, documentViewerKey);
        core.addEventListener('contentEditDocumentDigitallySigned', onContentEditDocumentDigitalSigned, undefined, documentViewerKey);
        core.addEventListener('contentEditModeEnded', onContentEditModeEnded, undefined, documentViewerKey);
        core.addEventListener('contentBoxEditStarted', onContentBoxEditStarted, undefined, documentViewerKey);
        core.addEventListener('contentBoxEditEnded', onContentBoxEditEnded, undefined, documentViewerKey);
        core.addEventListener('contentEditPasswordRequired', onContentEditPasswordRequired, undefined, documentViewerKey);
        // OfficeEditor and SpreadsheetEditor Not supported for MultiViewerMode
        core.addEventListener('selectionChanged', onSpreadsheetEditorSelectionChanged, undefined, documentViewerKey);
        core.addEventListener('selectedRangeStyleChanged', onSelectedRangeStyleChanged, undefined, documentViewerKey);
        core.addEventListener('spreadsheetEditorEditModeChanged', onSpreadsheetEditorEditModeChanged, undefined, documentViewerKey);
        core.addEventListener('spreadsheetEditorLoaded', openSpreadsheetEditorLoadingModal, undefined, documentViewerKey);
        core.addEventListener('spreadsheetEditorReady', closeSpreadsheetEditorLoadingModal, undefined, documentViewerKey);
        core.addEventListener('documentLoaded', setupCompositionInput, undefined, documentViewerKey);
        core.addEventListener('documentLoaded', configureEditorMode, undefined, documentViewerKey);
        // Only need one of these event listeners (state is synced for both sides)
        document.addEventListener('fullscreenchange', onFullScreenChange);
        document.addEventListener('mozfullscreenchange', onFullScreenChange);
        document.addEventListener('webkitfullscreenchange', onFullScreenChange);
        document.addEventListener('MSFullscreenChange', onFullScreenChange);
        core.addEventListener(Events.COMPARE_ANNOTATIONS_LOADED, onCompareAnnotationsLoaded, undefined, documentViewerKey);
        core.getTool('AnnotationCreateSignature', documentViewerKey).addEventListener('signatureSaved', onSignatureSaved);
        core.getTool('AnnotationCreateSignature', documentViewerKey).addEventListener('signatureDeleted', onSignatureDeleted);
        core.getTool('AnnotationCreateSignature', documentViewerKey).addEventListener('initialSaved', onInitialSaved);
        core.getTool('AnnotationCreateSignature', documentViewerKey).addEventListener('initialDeleted', onInitialDeleted);
        core.addEventListener('formFieldCreationModeEnded', onFormFieldCreationModeEnded, undefined, documentViewerKey);
        core.addEventListener('formFieldCreationModeStarted', onFormFieldCreationModeStarted, undefined, documentViewerKey);
        core.addEventListener('toolUpdated', onToolUpdated, undefined, documentViewerKey);
        core.addEventListener('toolModeUpdated', onToolModeUpdated, undefined, documentViewerKey);
        core.addEventListener('fitModeUpdated', onFitModeUpdated, undefined, documentViewerKey);
        // Legacy UI listeners will be deprecated soon
        core.addEventListener('documentLoaded', checkDocumentForTools, undefined, documentViewerKey);
        core.addEventListener('readOnlyModeChanged', onReadOnlyModeChanged, undefined, documentViewerKey);
        core.addEventListener('rotationUpdated', onRotationUpdated, undefined, documentViewerKey);
        core.addEventListener('updateAnnotationPermission', onUpdateAnnotationPermission, undefined, documentViewerKey);
        // Accessible Reading order mode not support by MultiViewer
        core.addEventListener('accessibleReadingOrderModeStarted', onAccessibleReadingOrderModeStarted, undefined, documentViewerKey);
        core.addEventListener('accessibleReadingOrderModeReady', onAccessibleReadingOrderModeReady, undefined, documentViewerKey);
        core.addEventListener('accessibleReadingOrderModeEnded', onAccessibleReadingOrderModeEnded, undefined, documentViewerKey);
        core.addEventListener('accessibleReadingOrderModeNoStructure', onAccessibleReadingOrderModeNoStructure, undefined, documentViewerKey);
      }
      core.getTool(ToolNames.ADD_IMAGE_CONTENT, documentViewerKey).addEventListener('annotationAdded', onImageContentAdded);
      core.addEventListener('documentLoaded', addPageLabelsToRedux, undefined, documentViewerKey);
      core.getTool('AnnotationCreateMarkInsertText', documentViewerKey).addEventListener('annotationAdded', onCaretAnnotationAdded);
      core.getTool('AnnotationCreateMarkInsertText2', documentViewerKey).addEventListener('annotationAdded', onCaretAnnotationAdded);
      core.getTool('AnnotationCreateMarkInsertText3', documentViewerKey).addEventListener('annotationAdded', onCaretAnnotationAdded);
      core.getTool('AnnotationCreateMarkInsertText4', documentViewerKey).addEventListener('annotationAdded', onCaretAnnotationAdded);
      core.getTool('AnnotationCreateMarkReplaceText', documentViewerKey).addEventListener('annotationAdded', onCaretAnnotationAdded);
      core.getTool('AnnotationCreateMarkReplaceText2', documentViewerKey).addEventListener('annotationAdded', onCaretAnnotationAdded);
      core.getTool('AnnotationCreateMarkReplaceText3', documentViewerKey).addEventListener('annotationAdded', onCaretAnnotationAdded);
      core.getTool('AnnotationCreateMarkReplaceText4', documentViewerKey).addEventListener('annotationAdded', onCaretAnnotationAdded);
      core.getTool('AnnotationCreateSticky', documentViewerKey).addEventListener('annotationAdded', onStickyAnnotationAdded);
      core.getTool('AnnotationCreateSticky2', documentViewerKey).addEventListener('annotationAdded', onStickyAnnotationAdded);
      core.getTool('AnnotationCreateSticky3', documentViewerKey).addEventListener('annotationAdded', onStickyAnnotationAdded);
      core.getTool('AnnotationCreateSticky4', documentViewerKey).addEventListener('annotationAdded', onStickyAnnotationAdded);
      core.addEventListener('documentLoaded', enableRedactionElements, { once: true }, documentViewerKey);
      core.addEventListener('documentLoaded', updatePortfolio, undefined, documentViewerKey);
      core.addEventListener('pageNumberUpdated', onPageNumberUpdated, undefined, documentViewerKey);
      core.addEventListener('documentLoaded', handlePasswordModal, undefined, documentViewerKey);
      core.addEventListener('documentLoaded', initializeLayersVisibility, undefined, documentViewerKey);
      core.addEventListener('documentLoaded', showProgressModal, undefined, documentViewerKey);
      core.addEventListener('documentLoaded', setPrintHandler, undefined, documentViewerKey);
      core.addEventListener('documentLoaded', toggleAnnotations, undefined, documentViewerKey);
      core.addEventListener('documentLoaded', setServerProperties, undefined, documentViewerKey);
      core.addEventListener('documentLoaded', syncDisplayModeMultiviewer, undefined, documentViewerKey);
      core.addEventListener('documentLoaded', updateOutlines, undefined, documentViewerKey);
      core.addEventListener('beforeDocumentLoaded', onBeforeDocumentLoaded, undefined, documentViewerKey);
      core.addEventListener('displayModeUpdated', onDisplayModeUpdated, undefined, documentViewerKey);
      core.addEventListener('documentLoaded', onDocumentLoaded, undefined, documentViewerKey);
      core.addEventListener('documentUnloaded', onDocumentUnloaded, undefined, documentViewerKey);
      core.addEventListener('zoomUpdated', onZoomUpdated, undefined, documentViewerKey);
      core.addEventListener('annotationChanged', onAnnotationChanged, undefined, documentViewerKey);
      core.addEventListener('historyChanged', onHistoryChanged, undefined, documentViewerKey);
      core.addEventListener('pagesUpdated', onPagesUpdated, undefined, documentViewerKey);
      core.addEventListener('pageComplete', onPageComplete, undefined, documentViewerKey);
      core.addEventListener('fileAttachmentDataAvailable', onFileAttachmentDataAvailable, undefined, documentViewerKey);
      core.addEventListener('userBookmarksChanged', onUserBookmarksChanged, undefined, documentViewerKey);
      core.addEventListener('widgetHighlightingChanged', onWidgetHighlightingChanged, undefined, documentViewerKey);
      core.getTool('AnnotationCreateStamp', documentViewerKey).addEventListener('annotationAdded', onStampAnnotationAdded);
      core.getTool('AnnotationCreateSignature', documentViewerKey).addEventListener('locationSelected', onLocationSelected);
      core.getTool('AnnotationCreateSignature', documentViewerKey).addEventListener('annotationAdded', onSignatureAnnotationAdded);
      core.getTool(ToolNames.FORM_FILL_DOT, documentViewerKey).addEventListener('annotationAdded', onDotStampAnnotationAdded);
      core.getTool('AnnotationCreateRubberStamp', documentViewerKey).addEventListener('annotationAdded', onRubberStampAnnotationAdded);
      core.getTool('AnnotationCreateRubberStamp', documentViewerKey).addEventListener('stampsUpdated', onRubberStampsUpdated);
      core.getTool('AnnotationCreateFileAttachment', documentViewerKey).addEventListener('annotationAdded', onFileAttachmentAnnotationAdded);
      core.getTool(ToolNames.FORM_FILL_CROSS, documentViewerKey).addEventListener('annotationAdded', onCrossStampAnnotationAdded);
      core.getTool(ToolNames.FORM_FILL_CHECKMARK, documentViewerKey).addEventListener('annotationAdded', onCheckStampAnnotationAdded);
    },
    removeEventHandlers: () => {
      if (documentViewerKey === 1) {
        // ContentEdit Not supported for MultiViewerMode
        core.removeEventListener('contentEditModeStarted', onContentEditModeStarted, documentViewerKey);
        core.removeEventListener('contentEditDocumentDigitallySigned', onContentEditDocumentDigitalSigned, documentViewerKey);
        core.removeEventListener('contentEditModeEnded', onContentEditModeEnded, documentViewerKey);
        core.removeEventListener('contentBoxEditStarted', onContentBoxEditStarted, documentViewerKey);
        core.removeEventListener('contentBoxEditEnded', onContentBoxEditEnded, documentViewerKey);
        core.removeEventListener('contentEditPasswordRequired', onContentEditPasswordRequired, documentViewerKey);
        // OfficeEditor and SpreadsheetEditor Not supported for MultiViewerMode
        core.removeEventListener('selectionChanged', onSpreadsheetEditorSelectionChanged, documentViewerKey);
        core.removeEventListener('selectedRangeStyleChanged', onSelectedRangeStyleChanged, documentViewerKey);
        core.removeEventListener('spreadsheetEditorEditModeChanged', onSpreadsheetEditorEditModeChanged, documentViewerKey);
        core.removeEventListener('spreadsheetEditorLoaded', openSpreadsheetEditorLoadingModal, documentViewerKey);
        core.removeEventListener('spreadsheetEditorReady', closeSpreadsheetEditorLoadingModal, documentViewerKey);
        core.removeEventListener('documentLoaded', setupCompositionInput, documentViewerKey);
        core.removeEventListener('documentLoaded', configureEditorMode, documentViewerKey);
        // Only need one of these event listeners (state is synced for both sides)
        document.removeEventListener('fullscreenchange', onFullScreenChange);
        document.removeEventListener('mozfullscreenchange', onFullScreenChange);
        document.removeEventListener('webkitfullscreenchange', onFullScreenChange);
        document.removeEventListener('MSFullscreenChange', onFullScreenChange);
        core.removeEventListener(Events.COMPARE_ANNOTATIONS_LOADED, onCompareAnnotationsLoaded, documentViewerKey);
        core.getTool('AnnotationCreateSignature', documentViewerKey).removeEventListener('signatureSaved', onSignatureSaved);
        core.getTool('AnnotationCreateSignature', documentViewerKey).removeEventListener('signatureDeleted', onSignatureDeleted);
        core.getTool('AnnotationCreateSignature', documentViewerKey).removeEventListener('initialSaved', onInitialSaved);
        core.getTool('AnnotationCreateSignature', documentViewerKey).removeEventListener('initialDeleted', onInitialDeleted);
        core.removeEventListener('formFieldCreationModeEnded', onFormFieldCreationModeEnded, documentViewerKey);
        core.removeEventListener('formFieldCreationModeStarted', onFormFieldCreationModeStarted, documentViewerKey);
        core.removeEventListener('toolUpdated', onToolUpdated, documentViewerKey);
        core.removeEventListener('toolModeUpdated', onToolModeUpdated, documentViewerKey);
        core.removeEventListener('fitModeUpdated', onFitModeUpdated, documentViewerKey);
        // Legacy UI listeners will be deprecated soon
        core.removeEventListener('documentLoaded', checkDocumentForTools, documentViewerKey);
        core.removeEventListener('readOnlyModeChanged', onReadOnlyModeChanged, documentViewerKey);
        core.removeEventListener('rotationUpdated', onRotationUpdated, documentViewerKey);
        core.removeEventListener('updateAnnotationPermission', onUpdateAnnotationPermission, documentViewerKey);
        // Accessible Reading order mode not support by MultiViewer
        core.removeEventListener('accessibleReadingOrderModeStarted', onAccessibleReadingOrderModeStarted, documentViewerKey);
        core.removeEventListener('accessibleReadingOrderModeReady', onAccessibleReadingOrderModeReady, documentViewerKey);
        core.removeEventListener('accessibleReadingOrderModeEnded', onAccessibleReadingOrderModeEnded, documentViewerKey);
        core.removeEventListener('accessibleReadingOrderModeNoStructure', onAccessibleReadingOrderModeNoStructure, documentViewerKey);
      }
      core.getTool(ToolNames.ADD_IMAGE_CONTENT, documentViewerKey).removeEventListener('annotationAdded', onImageContentAdded);
      core.removeEventListener('documentLoaded', addPageLabelsToRedux, documentViewerKey);
      core.getTool('AnnotationCreateMarkInsertText', documentViewerKey).removeEventListener('annotationAdded', onCaretAnnotationAdded);
      core.getTool('AnnotationCreateMarkInsertText2', documentViewerKey).removeEventListener('annotationAdded', onCaretAnnotationAdded);
      core.getTool('AnnotationCreateMarkInsertText3', documentViewerKey).removeEventListener('annotationAdded', onCaretAnnotationAdded);
      core.getTool('AnnotationCreateMarkInsertText4', documentViewerKey).removeEventListener('annotationAdded', onCaretAnnotationAdded);
      core.getTool('AnnotationCreateMarkReplaceText', documentViewerKey).removeEventListener('annotationAdded', onCaretAnnotationAdded);
      core.getTool('AnnotationCreateMarkReplaceText2', documentViewerKey).removeEventListener('annotationAdded', onCaretAnnotationAdded);
      core.getTool('AnnotationCreateMarkReplaceText3', documentViewerKey).removeEventListener('annotationAdded', onCaretAnnotationAdded);
      core.getTool('AnnotationCreateMarkReplaceText4', documentViewerKey).removeEventListener('annotationAdded', onCaretAnnotationAdded);
      core.getTool('AnnotationCreateSticky', documentViewerKey).removeEventListener('annotationAdded', onStickyAnnotationAdded);
      core.getTool('AnnotationCreateSticky2', documentViewerKey).removeEventListener('annotationAdded', onStickyAnnotationAdded);
      core.getTool('AnnotationCreateSticky3', documentViewerKey).removeEventListener('annotationAdded', onStickyAnnotationAdded);
      core.getTool('AnnotationCreateSticky4', documentViewerKey).removeEventListener('annotationAdded', onStickyAnnotationAdded);
      core.removeEventListener('documentLoaded', enableRedactionElements, documentViewerKey);
      core.removeEventListener('documentLoaded', updatePortfolio, documentViewerKey);
      core.removeEventListener('pageNumberUpdated', onPageNumberUpdated, documentViewerKey);
      core.removeEventListener('documentLoaded', handlePasswordModal, documentViewerKey);
      core.removeEventListener('documentLoaded', initializeLayersVisibility, documentViewerKey);
      core.removeEventListener('documentLoaded', showProgressModal, documentViewerKey);
      core.removeEventListener('documentLoaded', setPrintHandler, documentViewerKey);
      core.removeEventListener('documentLoaded', toggleAnnotations, documentViewerKey);
      core.removeEventListener('documentLoaded', setServerProperties, documentViewerKey);
      core.removeEventListener('documentLoaded', syncDisplayModeMultiviewer, documentViewerKey);
      core.removeEventListener('documentLoaded', updateOutlines, documentViewerKey);
      core.removeEventListener('beforeDocumentLoaded', onBeforeDocumentLoaded, documentViewerKey);
      core.removeEventListener('displayModeUpdated', onDisplayModeUpdated, documentViewerKey);
      core.removeEventListener('documentLoaded', onDocumentLoaded, documentViewerKey);
      core.removeEventListener('documentUnloaded', onDocumentUnloaded, documentViewerKey);
      core.removeEventListener('zoomUpdated', onZoomUpdated, documentViewerKey);
      core.removeEventListener('annotationChanged', onAnnotationChanged, documentViewerKey);
      core.removeEventListener('historyChanged', onHistoryChanged, documentViewerKey);
      core.removeEventListener('pagesUpdated', onPagesUpdated, documentViewerKey);
      core.removeEventListener('pageComplete', onPageComplete, documentViewerKey);
      core.removeEventListener('fileAttachmentDataAvailable', onFileAttachmentDataAvailable, documentViewerKey);
      core.removeEventListener('userBookmarksChanged', onUserBookmarksChanged, documentViewerKey);
      core.removeEventListener('widgetHighlightingChanged', onWidgetHighlightingChanged, documentViewerKey);
      core.getTool('AnnotationCreateStamp', documentViewerKey).removeEventListener('annotationAdded', onStampAnnotationAdded);
      core.getTool('AnnotationCreateSignature', documentViewerKey).removeEventListener('locationSelected', onLocationSelected);
      core.getTool('AnnotationCreateSignature', documentViewerKey).removeEventListener('annotationAdded', onSignatureAnnotationAdded);
      core.getTool(ToolNames.FORM_FILL_DOT, documentViewerKey).removeEventListener('annotationAdded', onDotStampAnnotationAdded);
      core.getTool('AnnotationCreateRubberStamp', documentViewerKey).removeEventListener('annotationAdded', onRubberStampAnnotationAdded);
      core.getTool('AnnotationCreateRubberStamp', documentViewerKey).removeEventListener('stampsUpdated', onRubberStampsUpdated);
      core.getTool('AnnotationCreateFileAttachment', documentViewerKey).removeEventListener('annotationAdded', onFileAttachmentAnnotationAdded);
      core.getTool(ToolNames.FORM_FILL_CROSS, documentViewerKey).removeEventListener('annotationAdded', onCrossStampAnnotationAdded);
      core.getTool(ToolNames.FORM_FILL_CHECKMARK, documentViewerKey).removeEventListener('annotationAdded', onCheckStampAnnotationAdded);
      !skipHotkeys && hotkeysManager.off();
    },
  };
};
