(function(){/*
 http://mths.be/fromcodepoint v0.1.0 by @mathias */
'use strict';function D(f){var a=0;return function(){return a<f.length?{done:!1,value:f[a++]}:{done:!0}}}var J="function"==typeof Object.defineProperties?Object.defineProperty:function(f,a,c){f!=Array.prototype&&f!=Object.prototype&&(f[a]=c.value)},L="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function N(){N=function(){};L.Symbol||(L.Symbol=P)}var P=function(){var f=0;return function(a){return"jscomp_symbol_"+(a||"")+f++}}();
function Q(){N();var f=L.Symbol.iterator;f||(f=L.Symbol.iterator=L.Symbol("iterator"));"function"!=typeof Array.prototype[f]&&J(Array.prototype,f,{configurable:!0,writable:!0,value:function(){return R(D(this))}});Q=function(){}}function R(f){Q();f={next:f};f[L.Symbol.iterator]=function(){return this};return f}function S(f){var a="undefined"!=typeof Symbol&&Symbol.iterator&&f[Symbol.iterator];return a?a.call(f):{next:D(f)}}function T(f){for(var a,c=[];!(a=f.next()).done;)c.push(a.value);return c}
function U(f,a,c){if(null==f)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(a instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return f+""}function V(f,a){if(a){var c=L;f=f.split(".");for(var b=0;b<f.length-1;b++){var d=f[b];d in c||(c[d]={});c=c[d]}f=f[f.length-1];b=c[f];a=a(b);a!=b&&null!=a&&J(c,f,{configurable:!0,writable:!0,value:a})}}
V("String.prototype.endsWith",function(f){return f?f:function(a,c){var b=U(this,a,"endsWith");a+="";void 0===c&&(c=b.length);c=Math.max(0,Math.min(c|0,b.length));for(var d=a.length;0<d&&0<c;)if(b[--c]!=a[--d])return!1;return 0>=d}});V("String.prototype.startsWith",function(f){return f?f:function(a,c){var b=U(this,a,"startsWith");a+="";var d=b.length,e=a.length;c=Math.max(0,Math.min(c|0,b.length));for(var m=0;m<e&&c<d;)if(b[c++]!=a[m++])return!1;return m>=e}});
V("String.fromCodePoint",function(f){return f?f:function(a){for(var c="",b=0;b<arguments.length;b++){var d=Number(arguments[b]);if(0>d||1114111<d||d!==Math.floor(d))throw new RangeError("invalid_code_point "+d);65535>=d?c+=String.fromCharCode(d):(d-=65536,c+=String.fromCharCode(d>>>10&1023|55296),c+=String.fromCharCode(d&1023|56320))}return c}});
function W(f,a){Q();f instanceof String&&(f+="");var c=0,b={next:function(){if(c<f.length){var d=c++;return{value:a(d,f[d]),done:!1}}b.next=function(){return{done:!0,value:void 0}};return b.next()}};b[Symbol.iterator]=function(){return b};return b}V("Array.prototype.keys",function(f){return f?f:function(){return W(this,function(a){return a})}});
(function(f){function a(b){if(c[b])return c[b].Db;var d=c[b]={Rg:b,If:!1,Db:{}};f[b].call(d.Db,d,d.Db,a);d.If=!0;return d.Db}var c={};a.Ba=f;a.Dg=c;a.d=function(c,d,e){a.Lf(c,d)||Object.defineProperty(c,d,{enumerable:!0,get:e})};a.r=function(a){N();N();"undefined"!==typeof Symbol&&Symbol.toStringTag&&(N(),Object.defineProperty(a,Symbol.toStringTag,{value:"Module"}));Object.defineProperty(a,"__esModule",{value:!0})};a.t=function(c,d){d&1&&(c=a(c));if(d&8||d&4&&"object"===typeof c&&c&&c.ne)return c;
var b=Object.create(null);a.r(b);Object.defineProperty(b,"default",{enumerable:!0,value:c});if(d&2&&"string"!=typeof c)for(var m in c)a.d(b,m,function(a){return c[a]}.bind(null,m));return b};a.n=function(c){var b=c&&c.ne?function(){return c["default"]}:function(){return c};a.d(b,"a",b);return b};a.Lf=function(a,c){return Object.prototype.hasOwnProperty.call(a,c)};a.p="/core/";return a(a.lh=1)})([function(f,a){function c(a,c,e,m,k,f){this.Oa=16;this.je=288;this.status=0;this.root=null;this.Ba=0;var v=
Array(this.Oa+1),h,g,l,q=Array(this.Oa+1),u,n=new b,p=Array(this.Oa);var r=Array(this.je);var t=Array(this.Oa+1),I,B;var K=this.root=null;for(g=0;g<v.length;g++)v[g]=0;for(g=0;g<q.length;g++)q[g]=0;for(g=0;g<p.length;g++)p[g]=null;for(g=0;g<r.length;g++)r[g]=0;for(g=0;g<t.length;g++)t[g]=0;var O=256<c?a[256]:this.Oa;var A=a;var z=0;g=c;do v[A[z]]++,z++;while(0<--g);if(v[0]==c)this.root=null,this.status=this.Ba=0;else{for(l=1;l<=this.Oa&&0==v[l];l++);var C=l;f<l&&(f=l);for(g=this.Oa;0!=g&&0==v[g];g--);
var M=g;f>g&&(f=g);for(I=1<<l;l<g;l++,I<<=1)if(0>(I-=v[l])){this.status=2;this.Ba=f;return}if(0>(I-=v[g]))this.status=2,this.Ba=f;else{v[g]+=I;t[1]=l=0;A=v;z=1;for(u=2;0<--g;)t[u++]=l+=A[z++];A=a;g=z=0;do 0!=(l=A[z++])&&(r[t[l]++]=g);while(++g<c);c=t[M];t[0]=g=0;A=r;z=0;r=-1;var y=q[0]=0;u=null;for(B=0;C<=M;C++)for(a=v[C];0<a--;){for(;C>y+q[1+r];){y+=q[1+r];r++;B=(B=M-y)>f?f:B;if((h=1<<(l=C-y))>a+1)for(h-=a+1,u=C;++l<B&&!((h<<=1)<=v[++u]);)h-=v[u];y+l>O&&y<O&&(l=O-y);B=1<<l;q[1+r]=l;u=Array(B);for(h=
0;h<B;h++)u[h]=new b;K=null==K?this.root=new d:K.next=new d;K.next=null;K.list=u;p[r]=u;0<r&&(t[r]=g,n.va=q[r],n.e=16+l,n.t=u,l=(g&(1<<y)-1)>>y-q[r],p[r-1][l].e=n.e,p[r-1][l].va=n.va,p[r-1][l].n=n.n,p[r-1][l].t=n.t)}n.va=C-y;z>=c?n.e=99:A[z]<e?(n.e=256>A[z]?16:15,n.n=A[z++]):(n.e=k[A[z]-e],n.n=m[A[z++]-e]);h=1<<C-y;for(l=g>>y;l<B;l+=h)u[l].e=n.e,u[l].va=n.va,u[l].n=n.n,u[l].t=n.t;for(l=1<<C-1;0!=(g&l);l>>=1)g^=l;for(g^=l;(g&(1<<y)-1)!=t[r];)y-=q[r],r--}this.Ba=q[1];this.status=0!=I&&1!=M?1:0}}}function b(){this.n=
this.va=this.e=0;this.t=null}function d(){this.list=this.next=null}var e=[0,1,3,7,15,31,63,127,255,511,1023,2047,4095,8191,16383,32767,65535],m=[3,4,5,6,7,8,9,10,11,13,15,17,19,23,27,31,35,43,51,59,67,83,99,115,131,163,195,227,258,0,0],k=[0,0,0,0,0,0,0,0,1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5,0,99,99],g=[1,2,3,4,5,7,9,13,17,25,33,49,65,97,129,193,257,385,513,769,1025,1537,2049,3073,4097,6145,8193,12289,16385,24577],h=[0,0,0,0,1,1,2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9,10,10,11,11,12,12,13,13],n=[16,17,
18,0,8,7,9,6,10,5,11,4,12,3,13,2,14,1,15],p={lc:function(a){this.$f();this.ic=a;this.jc=0}};p.lc.prototype={Od:function(a){for(var c,b=Array(1024),d=[],e=0;e<a&&0<(c=this.Zf(b,0,b.length));)d[d.length]=String.fromCharCode.apply(null,b.slice(0,c)),e+=c;return e?(this.ic=this.ic.slice(this.jc),this.jc=0,d.join("")):""},Vf:function(){return this.ic.length==this.jc?-1:this.ic.charCodeAt(this.jc++)&255},P:function(a){for(;this.$a<a;)this.sb|=this.Vf()<<this.$a,this.$a+=8},U:function(a){return this.sb&
e[a]},O:function(a){this.sb>>=a;this.$a-=a},hc:function(a,c,b){var d,e;if(0==b)return 0;for(e=0;;){this.P(this.ya);var m=this.Na.list[this.U(this.ya)];for(d=m.e;16<d;){if(99==d)return-1;this.O(m.va);d-=16;this.P(d);m=m.t[this.U(d)];d=m.e}this.O(m.va);if(16==d)this.fa&=32767,a[c+e++]=this.Ma[this.fa++]=m.n;else{if(15==d)break;this.P(d);this.la=m.n+this.U(d);this.O(d);this.P(this.rb);m=this.ae.list[this.U(this.rb)];for(d=m.e;16<d;){if(99==d)return-1;this.O(m.va);d-=16;this.P(d);m=m.t[this.U(d)];d=m.e}this.O(m.va);
this.P(d);this.ab=this.fa-m.n-this.U(d);for(this.O(d);0<this.la&&e<b;)this.la--,this.ab&=32767,this.fa&=32767,a[c+e++]=this.Ma[this.fa++]=this.Ma[this.ab++]}if(e==b)return b}this.La=-1;return e},ag:function(a,c,b){var d=this.$a&7;this.O(d);this.P(16);d=this.U(16);this.O(16);this.P(16);if(d!=(~this.sb&65535))return-1;this.O(16);this.la=d;for(d=0;0<this.la&&d<b;)this.la--,this.fa&=32767,this.P(8),a[c+d++]=this.Ma[this.fa++]=this.U(8),this.O(8);0==this.la&&(this.La=-1);return d},Yf:function(a,b,d){if(null==
this.gc){var e,f=Array(288);for(e=0;144>e;e++)f[e]=8;for(;256>e;e++)f[e]=9;for(;280>e;e++)f[e]=7;for(;288>e;e++)f[e]=8;this.Nc=7;e=new c(f,288,257,m,k,this.Nc);if(0!=e.status)return alert("HufBuild error: "+e.status),-1;this.gc=e.root;this.Nc=e.Ba;for(e=0;30>e;e++)f[e]=5;this.Mc=5;e=new c(f,30,0,g,h,this.Mc);if(1<e.status)return this.gc=null,alert("HufBuild error: "+e.status),-1;this.Wf=e.root;this.Mc=e.Ba}this.Na=this.gc;this.ae=this.Wf;this.ya=this.Nc;this.rb=this.Mc;return this.hc(a,b,d)},Xf:function(a,
b,d){var e,f,l,p=Array(316);for(e=0;e<p.length;e++)p[e]=0;this.P(5);var q=257+this.U(5);this.O(5);this.P(5);var r=1+this.U(5);this.O(5);this.P(4);e=4+this.U(4);this.O(4);if(286<q||30<r)return-1;for(f=0;f<e;f++)this.P(3),p[n[f]]=this.U(3),this.O(3);for(;19>f;f++)p[n[f]]=0;this.ya=7;f=new c(p,19,19,null,null,this.ya);if(0!=f.status)return-1;this.Na=f.root;this.ya=f.Ba;var E=q+r;for(e=l=0;e<E;){this.P(this.ya);var w=this.Na.list[this.U(this.ya)];f=w.va;this.O(f);f=w.n;if(16>f)p[e++]=l=f;else if(16==
f){this.P(2);f=3+this.U(2);this.O(2);if(e+f>E)return-1;for(;0<f--;)p[e++]=l}else{17==f?(this.P(3),f=3+this.U(3),this.O(3)):(this.P(7),f=11+this.U(7),this.O(7));if(e+f>E)return-1;for(;0<f--;)p[e++]=0;l=0}}this.ya=9;f=new c(p,q,257,m,k,this.ya);0==this.ya&&(f.status=1);if(0!=f.status)return-1;this.Na=f.root;this.ya=f.Ba;for(e=0;e<r;e++)p[e]=p[e+q];this.rb=6;f=new c(p,r,0,g,h,this.rb);this.ae=f.root;this.rb=f.Ba;return 0==this.rb&&257<q||0!=f.status?-1:this.hc(a,b,d)},$f:function(){null==this.Ma&&(this.Ma=
Array(65536));this.$a=this.sb=this.fa=0;this.La=-1;this.fc=!1;this.la=this.ab=0;this.gc=this.Na=null},Zf:function(a,c,b){var d;for(d=0;d<b&&(!this.fc||-1!=this.La);){if(0<this.la){if(0!=this.La)for(;0<this.la&&d<b;)this.la--,this.ab&=32767,this.fa&=32767,a[c+d++]=this.Ma[this.fa++]=this.Ma[this.ab++];else{for(;0<this.la&&d<b;)this.la--,this.fa&=32767,this.P(8),a[c+d++]=this.Ma[this.fa++]=this.U(8),this.O(8);0==this.la&&(this.La=-1)}if(d==b)break}if(-1==this.La){if(this.fc)break;this.P(1);0!=this.U(1)&&
(this.fc=!0);this.O(1);this.P(2);this.La=this.U(2);this.O(2);this.Na=null;this.la=0}switch(this.La){case 0:var e=this.ag(a,c+d,b-d);break;case 1:e=null!=this.Na?this.hc(a,c+d,b-d):this.Yf(a,c+d,b-d);break;case 2:e=null!=this.Na?this.hc(a,c+d,b-d):this.Xf(a,c+d,b-d);break;default:e=-1}if(-1==e)return this.fc?0:-1;d+=e}return d}};p.Rd=function(a){return(new p.lc(a)).Od(4E9)};a.a=p},function(f,a,c){f.Db=c(2)},function(f,a,c){c.r(a);c(3);c(4);f=c(5);c.n(f);c(6)},function(){var f=self,a=f.$d;(function(){function c(a){d?
d.push(a):setTimeout(a,0)}var b={version:"0.7.2.0",$g:function(a){return void 0===a},Zg:function(a){return null===a},wa:function(a){return null===a||void 0===a},ah:function(a){return null!==a&&void 0!==a}},d=[];f.attachEvent&&f.attachEvent("onload",function(){if(d){var a=d;d=null;for(var c=0,b=a.length;c<b;c++)a[c]()}});a||(f.$d=a={Za:c,ready:c});for(var e in b)a[e]=b[e]})();Object.na="Object";Object.Pa=null;Object.Gg=function(a){for(var c in a)delete a[c]};Object.Td=function(a,b){return void 0!==
a[b]};Object.keys?Object.Bf=function(a){return Object.keys(a).length}:(Object.keys=function(a){var c=[],d;for(d in a)c.push(d);return c},Object.Bf=function(a){var c=0,d;for(d in a)c++;return c});Boolean.na="Boolean";Boolean.parse=function(a){return"true"==a.toLowerCase()};Number.na="Number";Number.parse=function(a){return a&&a.length?0<=a.indexOf(".")||0<=a.indexOf("e")||a.endsWith("f")||a.endsWith("F")?parseFloat(a):parseInt(a,10):0};Number.prototype.format=function(c){return a.wa(c)||0==c.length||
"i"==c?this.toString():this.vd(c,!1)};Number.prototype.Vd=function(c){return a.wa(c)||0==c.length||"i"==c?this.toLocaleString():this.vd(c,!0)};Number.nc=function(a,b,d,e){var c=null;d=a.indexOf(d);0<d&&(c=a.substr(d),a=a.substr(0,d));(d=a.startsWith("-"))&&(a=a.substr(1));var f=0,g=b[f];if(a.length<g)return c?a+c:a;for(var h=a.length,n="",p=!1;!p;){var q=g,l=h-q;0>l&&(g+=l,q+=l,l=0,p=!0);if(!q)break;l=a.substr(l,q);n=n.length?l+e+n:l;h-=q;f<b.length-1&&(f++,g=b[f])}d&&(n="-"+n);return c?n+c:n};Number.prototype.vd=
function(c,b){b=b?a.be.bg.Kf:a.be.cg.Kf;var d="",e=-1;1<c.length&&(e=parseInt(c.substr(1)));c=c.charAt(0);switch(c){case "d":case "D":d=parseInt(Math.abs(this)).toString();-1!=e&&(d=d.Yd(e));0>this&&(d="-"+d);break;case "x":case "X":d=parseInt(Math.abs(this)).toString(16);"X"==c&&(d=d.toUpperCase());-1!=e&&(d=d.Yd(e));break;case "e":case "E":d=-1==e?this.toExponential():this.toExponential(e);"E"==c&&(d=d.toUpperCase());break;case "f":case "F":case "n":case "N":-1==e&&(e=b.bh);d=this.toFixed(e).toString();
e&&"."!=b.Xd&&(e=d.indexOf("."),d=d.substr(0,e)+b.Xd+d.substr(e+1));if("n"==c||"N"==c)d=Number.nc(d,b.eh,b.Xd,b.dh);break;case "c":case "C":-1==e&&(e=b.Kg);d=Math.abs(this).toFixed(e).toString();e&&"."!=b.Ld&&(e=d.indexOf("."),d=d.substr(0,e)+b.Ld+d.substr(e+1));d=Number.nc(d,b.Mg,b.Ld,b.Lg);d=0>this?String.format(b.Ng,d):String.format(b.Og,d);break;case "p":case "P":-1==e&&(e=b.fh),d=(100*Math.abs(this)).toFixed(e).toString(),e&&"."!=b.Zd&&(e=d.indexOf("."),d=d.substr(0,e)+b.Zd+d.substr(e+1)),d=
Number.nc(d,b.hh,b.Zd,b.gh),d=0>this?String.format(b.ih,d):String.format(b.jh,d)}return d};String.na="String";String.ce="";String.compare=function(a,b,d){d&&(a&&(a=a.toUpperCase()),b&&(b=b.toUpperCase()));a=a||"";b=b||"";return a==b?0:a<b?-1:1};String.concat=function(){return 2===arguments.length?arguments[0]+arguments[1]:Array.prototype.join.call(arguments,"")};String.prototype.endsWith=function(a){return a.length?a.length>this.length?!1:this.substr(this.length-a.length)==a:!0};String.Ja=function(a,
b,d){return 0==String.compare(a,b,d)};String.gd=function(c,b,d){String.hd||(String.hd=/(\{[^\}^\{]+\})/g);return c.replace(String.hd,function(c,f){c=b[parseInt(f.substr(1))+1];if(a.wa(c))return"";if(c.format){var e=null,m=f.indexOf(":");0<m&&(e=f.substring(m+1,f.length-1));return d?c.Vd(e):c.format(e)}return d?c.toLocaleString():c.toString()})};String.format=function(a){return String.gd(a,arguments,!1)};String.yf=function(a){for(var c="0",d=1;d<a;d++)c+="0";return c};String.Gf=function(a){return!a||
!a.length};String.Vd=function(a){return String.gd(a,arguments,!0)};String.prototype.Yd=function(a){return this.length<a?String.yf(a-this.length)+this:this};String.prototype.remove=function(a,b){return!b||a+b>this.length?this.substr(0,a):this.substr(0,a)+this.substr(a+b)};String.prototype.startsWith=function(a){return a.length?a.length>this.length?!1:this.substr(0,a.length)==a:!0};String.prototype.trim||(String.prototype.trim=function(){return this.Sf().Tf()});String.prototype.Sf=function(){return this.replace(/\s*$/,
"")};String.prototype.Tf=function(){return this.replace(/^\s*/,"")};Array.na="Array";Array.Lb=[a.Ib];Array.prototype.add=function(a){this.push(a)};Object.defineProperty(Array.prototype,"add",{enumerable:!1,writable:!0});Array.prototype.addRange=function(a){this.push.apply(this,a)};Object.defineProperty(Array.prototype,"addRange",{enumerable:!1,writable:!0});Object.defineProperty(Array.prototype,"aggregate",{enumerable:!1,writable:!0});Array.prototype.clear=function(){this.length=0};Object.defineProperty(Array.prototype,
"clear",{enumerable:!1,writable:!0});Array.prototype.clone=function(){return 1===this.length?[this[0]]:Array.apply(null,this instanceof Array?this:T(S(this)))};Object.defineProperty(Array.prototype,"clone",{enumerable:!1,writable:!0});Array.prototype.contains=function(a){return 0<=this.indexOf(a)};Object.defineProperty(Array.prototype,"contains",{enumerable:!1,writable:!0});Object.defineProperty(Array.prototype,"dequeue",{enumerable:!1,writable:!0});Array.prototype.enqueue=function(a){this.sf=!0;
this.push(a)};Object.defineProperty(Array.prototype,"enqueue",{enumerable:!1,writable:!0});Array.prototype.Z=function(){return this.length?this[this.sf?0:this.length-1]:null};Object.defineProperty(Array.prototype,"peek",{enumerable:!1,writable:!0});Array.prototype.every||(Array.prototype.every=function(a,b){for(var c=this.length,e=0;e<c;e++)if(e in this&&!a.call(b,this[e],e,this))return!1;return!0},Object.defineProperty(Array.prototype,"every",{enumerable:!1,writable:!0}));Object.defineProperty(Array.prototype,
"extract",{enumerable:!1,writable:!0});Array.prototype.filter||(Array.prototype.filter=function(a,b){for(var c=this.length,e=[],f=0;f<c;f++)if(f in this){var k=this[f];a.call(b,k,f,this)&&e.push(k)}return e},Object.defineProperty(Array.prototype,"filter",{enumerable:!1,writable:!0}));Array.prototype.forEach||(Array.prototype.forEach=function(a,b){for(var c=this.length,e=0;e<c;e++)e in this&&a.call(b,this[e],e,this)},Object.defineProperty(Array.prototype,"forEach",{enumerable:!1,writable:!0}));Array.prototype.Ya=
function(){return new a.Gb(this)};Object.defineProperty(Array.prototype,"getEnumerator",{enumerable:!1,writable:!0});Object.defineProperty(Array.prototype,"groupBy",{enumerable:!1,writable:!0});Array.prototype.index=function(a,b){for(var c=this.length,e={},f=0;f<c;f++)if(f in this){var k=a.call(b,this[f],f);String.Gf(k)||(e[k]=this[f])}return e};Object.defineProperty(Array.prototype,"index",{enumerable:!1,writable:!0});Array.prototype.indexOf||(Array.prototype.indexOf=function(a,b){var c=this.length;
if(c)for(b=b||0;b<c;b++)if(this[b]===a)return b;return-1},Object.defineProperty(Array.prototype,"indexOf",{enumerable:!1,writable:!0}));Object.defineProperty(Array.prototype,"insert",{enumerable:!1,writable:!0});Object.defineProperty(Array.prototype,"insertRange",{enumerable:!1,writable:!0});Array.prototype.map||(Array.prototype.map=function(a,b){for(var c=this.length,e=Array(c),f=0;f<c;f++)f in this&&(e[f]=a.call(b,this[f],f,this));return e},Object.defineProperty(Array.prototype,"map",{enumerable:!1,
writable:!0}));Array.prototype.remove=function(a){a=this.indexOf(a);return 0<=a?(this.splice(a,1),!0):!1};Object.defineProperty(Array.prototype,"remove",{enumerable:!1,writable:!0});Array.prototype.Jc=function(a){this.splice(a,1)};Object.defineProperty(Array.prototype,"removeAt",{enumerable:!1,writable:!0});Array.prototype.removeRange=function(a,b){return this.splice(a,b)};Object.defineProperty(Array.prototype,"removeRange",{enumerable:!1,writable:!0});Array.prototype.some||(Array.prototype.some=
function(a,b){for(var c=this.length,e=0;e<c;e++)if(e in this&&a.call(b,this[e],e,this))return!0;return!1},Object.defineProperty(Array.prototype,"some",{enumerable:!1,writable:!0}));Array.Rf=function(a){return Array.prototype.slice.call(a)};RegExp.na="RegExp";RegExp.parse=function(a){if(a.startsWith("/")){var c=a.lastIndexOf("/");if(1<c)return new RegExp(a.substring(1,c),a.substr(c+1))}return null};Error.na="Error";Error.prototype.Mf=function(){if(!(a.wa(this.stack)||a.wa(this.fileName)||a.wa(this.lineNumber))){for(var c=
this.stack.split("\n"),b=c[0],d=this.fileName+":"+this.lineNumber;!a.wa(b)&&-1===b.indexOf(d);)c.shift(),b=c[0];b=c[1];isNullOrUndefined(b)||(b=b.match(/@(.*):(\d+)$/),a.wa(b)||(c.shift(),this.stack=c.join("\n"),this.fileName=b[1],this.lineNumber=parseInt(b[2])))}};Error.Ig=function(a,b,d){a=Error(a);if(b)for(var c in b)a[c]=b[c];d&&(a.Sg=d);a.Mf();return a};f.M=Function;f.M.na="Type";f.Tc=function(a){this.na=a};f.Tc.prototype={oe:!0,getName:function(){return this.na}};f.M.Nf=function(){f.mc||(f.mc=
{});f.Xc||(f.Xc=[]);if(!f.mc.trn){for(var a=self,b=["trn"],d=0;d<b.length;d++){var e=b[d],m=a[e];m||(a[e]=m=new f.Tc(b.slice(0,d+1).join(".")),0==d&&f.Xc.add(m));a=m}f.mc.trn=a}};f.M.prototype.ca=function(a,b,d){this.prototype.constructor=this;this.na=a;this.Uc=!0;this.Pa=b||Object;b&&(this.Kb=!0);if(d){this.Lb=[];for(var c=2;c<arguments.length;c++)d=arguments[c],this.Lb.add(d)}};f.M.prototype.Ka=function(a){this.na=a;this.Wc=!0};f.M.prototype.Kc=function(){if(this.Kb){var a=this.Pa;a.Kb&&a.Kc();
for(var b in a.prototype){var d=a.prototype[b];this.prototype[b]||(this.prototype[b]=d)}delete this.Kb}};f.M.prototype.Of||(f.M.prototype.Of=f.M.prototype.Kc);f.M.prototype.Ef=function(a){this.Kb&&this.Kc();this.Pa.apply(a)};f.M.prototype.Sd=function(c){return a.wa(c)?!1:this==Object||c instanceof this?!0:this.Ff(f.M.Af(c))};f.M.prototype.Ff=function(a){if(this==Object||this==a)return!0;if(this.Uc)for(a=a.Pa;a;){if(this==a)return!0;a=a.Pa}else if(this.Wc){var c=a.Lb;if(c&&c.contains(this))return!0;
for(a=a.Pa;a;){if((c=a.Lb)&&c.contains(this))return!0;a=a.Pa}}return!1};f.M.Ug=function(a){return 1==a.Uc};f.M.Vg=function(a){return 1==a.me};f.M.Wg=function(a){return 1==a.me&&1==a.Vc};f.M.Xg=function(a){return 1==a.Wc};f.M.Yg=function(a){return 1==a.oe};f.M.Eg=function(a,b){return b.Sd(a)};f.M.mh=function(a,b){return b.Sd(a)?a:null};f.M.Af=function(a){var c=null;try{c=a.constructor}catch(d){}c&&c.na||(c=Object);return c};a.kc=function(){};a.kc.ca("Enum");a.kc.parse=function(a,b){var c=a.prototype;
if(a.Vc){a=b.split("|");b=0;for(var e=!0,f=a.length-1;0<=f;f--){var k=a[f].trim(),g=!1;for(h in c)if(h===k){b|=c[h];g=!0;break}if(!g){e=!1;break}}if(e)return b}else for(var h in c)if(h===b)return c[h];throw"Invalid Enumeration Value";};a.kc.lg=function(a){var c=this.prototype;if(this.Vc&&0!==a){var d=[];for(e in c)c[e]&a&&(d.length&&d.add(" | "),d.add(e));if(!d.length)throw"Invalid Enumeration Value";return d.join("")}for(var e in c)if(c[e]===a)return e;throw"Invalid Enumeration Value";};a.$=function(){};
a.$.ca("Delegate");a.$.empty=function(){};a.$.te=function(a,b,d){for(var c=0;c<a.length;c+=2)if(a[c]===b&&a[c+1]===d)return!0;return!1};a.$.oc=function(c){function b(){if(2==c.length)return c[1].apply(c[0],arguments);for(var b=c.clone(),e=0;e<b.length;e+=2)a.$.te(c,b[e],b[e+1])&&b[e+1].apply(b[e],arguments);return null}b.Aa=c;return b};a.$.create=function(c,b){return c?a.$.oc([c,b]):b};a.$.Hg=function(c,b){return c?b?a.$.oc((c.Aa?c.Aa:[null,c]).concat(b.Aa?b.Aa:[null,b])):c.Aa?c:a.$.create(null,c):
b.Aa?b:a.$.create(null,b)};a.$.remove=function(c,b){if(!c||c===b)return null;if(!b)return c;var d=c.Aa,e=null;b.Aa&&(e=b.Aa[0],b=b.Aa[1]);for(var f=0;f<d.length;f+=2)if(d[f]===e&&d[f+1]===b){if(2==d.length)return null;d.splice(f,2);return a.$.oc(d)}return c};a.$.Jg=function(a,b,d){d=d||"__"+(new Date).valueOf();self[d]=b?a:function(){try{delete self[d]}catch(e){self[d]=void 0}a.apply(null,arguments)};return d};a.$.Pg=function(a){delete self[a]};a.$.Fg=function(c){self[c]=a.$.empty};a.tb=function(){};
a.tb.prototype={Wd:null,reset:null};a.tb.Ya=function(c){return c?c.Ya?c.Ya():new a.Gb(c):null};a.tb.Ka("IEnumerator");a.Ib=function(){};a.Ib.prototype={Ya:null};a.Ib.Ka("IEnumerable");a.Gb=function(a){this.Yc=a;this.Fa=-1;this.current=null};a.Gb.prototype={Wd:function(){this.Fa++;this.current=this.Yc[this.Fa];return this.Fa<this.Yc.length},reset:function(){this.Fa=-1;this.current=null}};a.Gb.ca("ArrayEnumerator",null,a.tb);a.Pc=function(){};a.Pc.prototype={wf:null};a.Pc.Ka("IDisposable");a.Rc=function(c){this.Cc=
a.wa(c)?[]:[c]};a.Rc.prototype={append:function(c){a.wa(c)||this.Cc.add(c);return this},clear:function(){this.Cc=[]},toString:function(a){return this.Cc.join(a||"")}};a.Rc.ca("StringBuilder");a.Hb=function(){};a.Hb.ca("EventArgs");a.Hb.ce=new a.Hb;f.XMLHttpRequest||(f.XMLHttpRequest=function(){for(var a=["Msxml2.XMLHTTP","Microsoft.XMLHTTP"],b=0;b<a.length;b++)try{return new ActiveXObject(a[b])}catch(d){}return null});a.Oc=function(){a.Oc.Ef(this);this.cancel=!1};a.Oc.ca("CancelEventArgs",a.Hb);a.ke=
function(a,b){this.first=a;this.second=b};a.ke.ca("Tuple");a.ma=function(){this.Bb=null};a.ma.prototype={};a.ma.Bc=[];a.ma.lf={wf:function(){a.ma.Bc.pop()}};a.ma.kh=function(c){a.ma.Bc.push(c);return a.ma.lf};a.ma.re=function(c){var b=a.ma.Bc,d=b.length;if(d){c=c||[];for(var e=0;e<d;e++){var f=b[e];c.contains(f)||c.push(f)}return c}return null};a.ma.hf=function(a){for(var c=0,d=a.length;c<d;c++)a[c].Tg()};a.ma.ca("Observable");a.Qc=function(a){this.Ga=a||[];this.Bb=null};a.Qc.prototype={add:function(a){this.Ga.push(a);
this.bc()},clear:function(){this.Ga.clear();this.bc()},contains:function(a){return this.Ga.contains(a)},Ya:function(){this.Bb=a.ma.re(this.Bb);return this.Ga.Ya()},indexOf:function(a){return this.Ga.indexOf(a)},remove:function(a){return this.Ga.remove(a)?(this.bc(),!0):!1},Jc:function(a){this.Ga.Jc(a);this.bc()},Rf:function(){return this.Ga},bc:function(){var c=this.Bb;c&&(this.Bb=null,a.ma.hf(c))}};a.Qc.ca("ObservableCollection",null,a.Ib);a.de=function(){};a.de.Ka("IApplication");a.ee=function(){};
a.ee.Ka("IContainer");a.he=function(){};a.he.Ka("IObjectFactory");a.fe=function(){};a.fe.Ka("IEventManager");a.ge=function(){};a.ge.Ka("IInitializable")},function(){(function(f){function a(a){this.depth=this.index=0;this.J=a;this.location={start:0,cc:1,dc:1,end:a.length,empty:!0};this.Eb=[this.location];this.Hc=!1;"?"===this.J.charAt(1)&&this.Qd();this.location.empty=!1}f.Jb=f.Jb?f.Jb:{};f.Jb.Uf=function(a){if(a)return a.replace(/&[^;]*;/g,function(a){switch(a.charAt(1)){case "q":return'"';case "a":return"&";
case "l":return"<";case "g":return">";case "#":return"x"===a.charAt(2)?String.fromCharCode(parseInt(a.substring(3,a.length-1),16)):String.fromCharCode(parseInt(a.substring(2,a.length-1),10))}return a})};a.prototype={advance:function(){this.Ia=null;this.Qd();var a=this.location.start;++a;this.location.empty=!1;if("/"!==this.J.charAt(a))return this.location.empty="/"===this.J.charAt(this.J.indexOf(">",a)-1),!0;this.location.end=!0;return!1},Ud:function(){var a=this.location.start+1,b=this.J.indexOf(">",
a);this.location.empty&&--b;a=this.J.substring(a,b);this.Ia={};b=a.indexOf(" ");if(-1!==b){this.Nd=a.substring(0,b);a=a.slice(b);a=a.split('"');b=a.length-1;for(var d=0;d<b;++d){var e=a[d],f=a[++d];this.Ia[e.substring(1,e.length-1)]=f}}else this.Nd=a},Qd:function(){if(this.Hc)this.Hc=!1,this.location.start=this.J.indexOf("<",this.location.start+1);else{var a=this.location.cc;if(!this.location.empty)for(var b=this.location.dc;0<b;)a=this.J.indexOf("<",a),"/"===this.J.charAt(++a)?--b:(a=this.J.indexOf(">",
a),"/"!==this.J.charAt(a-1)&&++b);this.location.start=this.J.indexOf("<",a)}this.location.cc=this.location.start+1;this.location.dc=1},mark:function(){this.J.mark&&this.J.mark(this.location.start)},L:function(){null!==this.Ia&&"undefined"!==typeof this.Ia||this.Ud();return this.Nd},G:function(){++this.depth;this.location={start:this.location.start};this.Eb[this.Eb.length]=this.location;this.Hc=!0},F:function(){--this.depth;this.Ia=null;var a=this.location.cc,b=this.location.dc,d=this.location.empty,
e=this.location.end;this.Eb.pop();this.location=this.Eb[this.Eb.length-1];this.location.cc=a;this.location.dc=e?0:d?b:b+1},T:function(){return this.location.empty?!0:"/"===this.J.charAt(this.J.indexOf("<",this.location.start+1)+1)},A:function(a){null!==this.Ia&&"undefined"!==typeof this.Ia||this.Ud();return f.Jb.Uf(this.Ia[a])}};f.le=a})(self)},function(){(function(){function f(a,c){this.o=[];this.s=[];a&&this.I(a,c)}self.M.Nf();String.fromCodePoint||function(){function a(){var a=[],c=-1,f=arguments.length;
if(!f)return"";for(var g="";++c<f;){var h=Number(arguments[c]);if(!isFinite(h)||0>h||1114111<h||d(h)!==h)throw RangeError("Invalid code point: "+h);if(65535>=h)a.push(h);else{h-=65536;var n=(h>>10)+55296;h=h%1024+56320;a.push(n,h)}if(c+1===f||16384<a.length)g+=b.apply(null,a instanceof Array?a:T(S(a))),a.length=0}return g}var c=function(){try{var a={},b=Object.defineProperty;var c=b(a,a,a)&&b}catch(g){}return c}(),b=String.fromCharCode,d=Math.floor;c?c(String,"fromCodePoint",{value:a,configurable:!0,
writable:!0}):String.fromCodePoint=a}();Array.prototype.Ja&&console.warn("Overriding existing Array.prototype.equals. Possible causes: New API defines the method, there's a framework conflict or you've got double inclusions in your code.");Array.prototype.Ja=function(a){if(!a||this.length!==a.length)return!1;for(var c=0,b=this.length;c<b;c++)if(this[c]instanceof Array&&a[c]instanceof Array){if(!this[c].Ja(a[c]))return!1}else if(this[c]!==a[c])return!1;return!0};Object.defineProperty(Array.prototype,
"equals",{enumerable:!1,writable:!0});f.prototype={v:function(a){this.o=this.o.concat(a.o);this.s=this.s.concat(a.s)},I:function(a,c){this.o.push(a);a=typeof c;this.s.push("object"===a?c:"undefined"===a?null:[c])},Ja:function(a){return this.o.Ja(a.o)&&this.s.Ja(a.s)},save:function(){this.o.push(trn.b.Se);this.s.push(null)},restore:function(){this.I(trn.b.Re,null)}};trn.b=function(a,c,b,d){this.done=!1;this.pd=2E3;this.Ta={};this.Va=0;this.N=[];this.Ub=[];this.ia=[];this.ia.add({});this.c=a;this.td=
this.Fb("Width");this.sd=this.Fb("Height");this.N.push(trn.Ra.Df(this.td,this.sd));this.ha=!1;this.od=c;this.Tb=b;this.jf=-1<navigator.userAgent.indexOf("Android")&&-1===navigator.userAgent.indexOf("Chrome")&&-1===navigator.userAgent.indexOf("Firefox");this.o=[];this.s=[];this.c.G();this.c.advance();this.Gc=d;a=this.c.L();trn.b.i(a,"FixedPage.Resources")&&(this.c.G(),this.c.advance(),this.Ad(),this.c.F());this.Sa=!1};trn.b.i=function(a,c){var b=trn.b.vf;return a===c?!0:a===b+c};trn.b.Md=function(a){return trn.b.xf(a)};
trn.b.xf=function(a){var c=3,b=Math.abs(a);.5>b&&(c=5E-4>b?5E-7>b?9:7:5);c=Math.pow(10,c);a=Math.round(a*c)/c;return a.toString()};trn.b.D=function(a,c){if(!a)throw Error(c);};trn.b.Qg=function(a){return(new trn.b(a,!1)).Ye()};trn.b.prototype={ef:function(){return this.uc()},pc:function(a,c){var b=this.Xe(),d=this.c.L();if(trn.b.i(d,"Path"))var e=this.sc();else trn.b.i(d,"Canvas")?e=this.Qb():trn.b.i(d,"Glyphs")?e=this.rc():(e=null,trn.b.D(!1,"Invalid Element "+d));e.pb(b);if(e.Hf()){b=this.ef();
d=this.fb();b.mtx=[d.V,d.W,d.X,d.Y,d.da,d.ea];if(a){a={operators:a.o,data:a.s};var f=this.c.A("RenderTransform");if(null!=f){var k=new trn.H;k.aa(f);f=new trn.H;f.vc(d);f.Qa(k);d=f}a.mtx=[d.V,d.W,d.X,d.Y,d.da,d.ea]}this.I(trn.b.Ve,[b,{x1:e.l,y1:e.m,x2:e.l+e.C,y2:e.m+e.B},c,a]);this.ud=!0}else this.ha=!1},Qb:function(){var a=new trn.ga;this.ba();var c=this.c.A("RenderTransform");if(null!=c){var b=new trn.H;b.aa(c);this.R(b)}c=this.c.A("Clip");null!=c&&(a=this.Da(c));c=null;if(!this.c.T()){for(this.c.G();this.c.advance();)b=
this.c.L(),trn.b.i(b,"Canvas.Clip")?(trn.b.D(!this.c.T(),"Canvas.Clip: Must contain PathGeometry element"),this.c.G(),this.c.advance()&&(b=new trn.H,b.aa(this.u("Transform")),this.R(b),a.pb(this.Da(this.u("Figures"))),b=b.gb(),this.R(b)),this.c.F()):trn.b.i(b,"Path")?null!=c?c.Lc(this.sc()):c=this.sc():trn.b.i(b,"Glyphs")?null!=c?c.Lc(this.rc()):c=this.rc():trn.b.i(b,"Canvas")&&(null!=c?c.Lc(this.Qb()):c=this.Qb());this.c.F()}null!=c&&a.pb(c);this.ra();return a},nf:function(){var a=this.xa("trn:BlendMode",
"source-over");a=this.ha?"source-over":a;var c=this.Dc();c||(this.save(),this.ba());var b=null,d=this.c.A("OpacityMask");null!=d&&(console.warn("Uh oh OpacityMask Resource!"),b=this.Ea(d));if(!this.c.T()){for(this.c.G();this.c.advance();)if(d=this.c.L(),trn.b.i(d,"Canvas.Resources"))this.c.T()?trn.b.D(!1,"Canvas.Resources must contain ResourceDictionary element"):(this.c.G(),this.c.advance(),this.Ad(),this.c.F());else if(trn.b.i(d,"Canvas.Clip"))trn.b.D(!this.c.T(),"Canvas.Clip: Must contain PathGeometry element"),
this.c.G(),this.c.advance()&&(c||(this.save(),c=!0,this.ba()),d=new trn.H,d.aa(this.u("Transform")),this.v(this.R(d)),trn.b.D(trn.b.i(this.c.L(),"PathGeometry"),"Path.Clip must contain PathGeometry"),this.ac(this.u("Figures")),d=d.gb(),this.v(this.R(d))),this.c.F();else if(trn.b.i(d,"Canvas.OpacityMask"))this.ha||(this.c.G(),this.c.advance(),b=this.eb(trn.b.oa,new f(trn.b.Nb)),this.c.F());else if(trn.b.i(d,"Path")||trn.b.i(d,"Glyphs")||trn.b.i(d,"Canvas")||trn.b.i(d,"trn:Glyphs")){if(null!=b||"source-over"!==
a){this.Cb();this.c.F();this.ha=!0;this.pc(b,a);return}this.Sa=!1;break}this.Sa&&this.c.F()}this.Sa&&this.Cb();this.ha=!1},Cb:function(){this.restore();this.ra()},Fb:function(a){a=this.c.A(a);trn.b.D(null!=a,this.c.L()+": "+a+" is not defined");return parseFloat(a)},sa:function(a,c){a=this.c.A(a);return null!=a?parseFloat(a):c},u:function(a){a=this.c.A(a);trn.b.D(null!=a,this.c.L()+": "+a+" is not defined");return a},xa:function(a,c){a=this.c.A(a);return null!=a?a:c},Pd:function(){var a=this.c.A("x:Key");
trn.b.D(null!=a,"Key must be defined for elements in a resource dictionary");return a},Dc:function(){0===this.Va&&this.c.mark();var a=!1,c=this.sa("Opacity",1);1>c&&(a||(a=!0,this.save(),this.ba()),this.v(this.cb(c)));c=this.c.A("RenderTransform");null!=c&&(a||(a=!0,this.save(),this.ba()),this.qf(c));c=this.c.A("Clip");null!=c&&(a||(this.save(),this.ba()),this.ac(c),a=!0);return a},ac:function(a){var c=!0;a&&"F"===a[0]&&(c=!1);this.Cd(c?"evenodd":"nonzero");this.gf(this.Da(a));this.yd(a);this.o.push(trn.b.xe);
this.s.push(c?["evenodd"]:[])},mf:function(a){var c=[];for(a=self.$d.tb.Ya(a.split(";"));a.Wd();){var b=a.current,d=new trn.Fa;b=b.split(",");if(1<=b.length){if(0<b[0].length){var e=b[0].split(")");if(2<=e.length){var f=e[0].substr(1).split(":");d.Vb=parseInt(f[0]);d.xc=parseInt(f[1])}d.Yb=parseInt(e[e.length-1]);d.Ab=!0}2<=b.length&&(0<b[1].length&&(d.wc=parseFloat(b[1]),d.zc=!0),3<=b.length&&(0<b[2].length&&(d.Zb=parseFloat(b[2])),4<=b.length&&0<b[3].length&&(d.$b=parseFloat(b[3]))))}c.add(d)}return c},
ff:function(){var a=this.u("UnicodeString"),c="",b=0;for(2<=a.length&&"{"===a.charAt(0)&&"}"===a.charAt(1)&&(a=a.substr(2));b<a.length;){var d=a.charCodeAt(b);if(9==d)c+=String.fromCharCode(10),b++;else if(128>d)c+=String.fromCharCode(d),b++;else if(191<d)if(224>d){var e=a.charCodeAt(b+1);c+=String.fromCharCode((d&31)<<6|e&63);b+=2}else if(240>d){e=a.charCodeAt(b+1);var f=a.charCodeAt(b+2);c+=String.fromCharCode((d&15)<<12|(e&63)<<6|f&63);b+=3}else e=a.charCodeAt(b+1),f=a.charCodeAt(b+2),c4=a.charCodeAt(b+
3),c+=String.fromCodePoint((d&7)<<18|(e&63)<<12|(f&63)<<6|c4&63),b+=4;else console.warn("Invalid UTF-8 character")}return c},rc:function(){var a=new trn.ga,c=this.c.A("Clip");null!=c&&(a=this.Da(c));return a},tc:function(a,c){return this.jf&&1===a.length?c===trn.b.ad?trn.b.De:c===trn.b.qc?trn.b.qc:trn.b.Ee:c},Sc:function(a){return 0===Object.keys(a).length&&a.constructor===Object},xd:function(a){var c=this.xa("trn:BlendMode","source-over");c=this.ha?"source-over":c;var b="source-over"!=c&&!this.Tb,
d=this.Dc();this.Tb&&this.Bd(c);var e=this.Fb("OriginX"),m=this.Fb("OriginY"),k=this.u("FontUri");this.xb[k]=null;var g=this.Fb("FontRenderingEmSize"),h=this.mf(this.xa("Indices",""));if(200>g){var n=g/200;d||(this.ba(),this.save(),d=!0);var p=new trn.H;p.vb(n,0,0,n,e,m);g=200;m=0;this.o.push(trn.b.Pb);this.s.push(p.Rb())}var q=0;e=new f;var l=this.ff(),r=0,v=0,u=g/100,t="",F=null;a=(p=this.c.A("Stroke"))?trn.b.qc:a?trn.b.ad:trn.b.Ce;e.I(trn.b.Te,0);for(var G={},x,E=0;E<h.length;){var w=h[E],H=l.charCodeAt(q);
H=w.Vb+(55296<=H&&57344>H?1:0);if(r!==w.Zb||v!==w.$b)t&&(e.I(this.tc(x,a),[t,r?r*u:0,m-v*u]),e.I(trn.b.cd,[t])),r=w.Zb,v=w.$b,t="";w.Ab&&(G[t.length]=l.substr(q,w.Vb));w.zc?(this.Sc(G)||e.I(trn.b.fd,[G]),x=t+(w.Ab?String.fromCharCode(w.Yb+57344):l.substr(q,H)),e.I(this.tc(x,a),[x,r?r*u:0,m-v*u]),t&&e.I(trn.b.cd,[t]),e.I(trn.b.ue,[w.wc*u]),G={},t=""):t+=w.Ab?String.fromCharCode(w.Yb+57344):l.substr(q,H);E+=w.xc;q+=H}if(t||q<l.length)this.Sc(G)||e.I(trn.b.fd,[G]),x=t+l.substr(q,l.length-q),e.I(this.tc(x,
a),[x,0,0]);m=x=null;r=this.c.A("Fill");q=!1;null!=r&&(this.Sb(r)?x=this.Ea(r,trn.b.oa,e):(q=!0,x=this.ub(r,trn.b.oa,e)));h=!1;null!=p&&(this.Sb(p)?F=this.Ea(p,trn.b.Ca,e):(h=!0,F=this.ub(p,trn.b.Ca,e)));r=this.c.A("OpacityMask");null!=r&&(console.warn("Uh oh OpacityMask Resource!"),m=this.Ea(r));if(!this.c.T()&&!a){for(this.c.G();this.c.advance();)a=this.c.L(),trn.b.i(a,"Glyphs.Clip")?(trn.b.D(!this.c.T(),"Canvas.Clip: Must contain PathGeometry element"),this.c.G(),this.c.advance()&&(d||(d=!0,this.save(),
this.ba()),p=new trn.H,p.aa(this.u("Transform")),this.o.push(trn.b.Pb),this.s.push(p.Rb()),trn.b.D(trn.b.i(this.c.L(),"PathGeometry"),"Path.Clip must contain PathGeometry"),a=this.u("Figures"),this.ac(a),p=p.gb(),this.o.push(trn.b.Pb),this.s.push(p.Rb())),this.c.F()):trn.b.i(a,"Glyphs.Fill")?(this.c.G(),this.c.advance(),x=this.eb(trn.b.oa,e),this.c.F()):trn.b.i(a,"Glyphs.OpacityMask")&&!this.ha&&(this.c.G(),this.c.advance(),m=this.eb(trn.b.oa,new f(trn.b.Nb)),this.c.F());this.c.F()}if(null==m||b)"otf"===
k.substr(k.indexOf(".")+1)?(k=k.substr(0,k.length-4),k=parseInt(k.substr(7))):k=parseInt(k.substr(35,8),16),k="f"+this.Gc+"-"+k,Object.Td(this.Ta,k)?10>this.Ta[k].length&&(this.Ta[k]+=l.substr(0,10-this.Ta[k].length)):this.Ta[k]=l.substr(0,10),this.tf(trn.b.Md(g)+"px "+k),null!==x&&(q||(x=new f(trn.b.oa,"#000000"),x.v(e)),this.Ec(x,e)),null!=F&&(g=this.sa("StrokeThickness",1),r=this.c.A("RenderTransform"),l=new trn.H,null!=r&&l.aa(r),this.Fc(g/(n*l.Xa())),this.Dd(this.ld(this.xa("StrokeStartLineCap",
"Flat"))),this.Ed(this.xa("StrokeLineJoin","miter").toLowerCase()),this.Fd(this.sa("StrokeMiterLimit",10)),h||(F=new f(trn.b.Ca,"#000000"),F.v(e)),this.Gd(F,e));d&&(this.restore(),this.ra());if(null!=m||b)this.ha=!0,this.pc(m,c);this.ha=!1},kd:function(){var a=[];this.c.G();trn.b.D(this.c.advance(),"Gradient brushes must contain GradientStops");for(this.c.G();this.c.advance();){var c=this.u("Color"),b=this.u("Offset");a.push(b);a.push(this.jd(c))}this.c.F();this.c.F();return a},af:function(a,c,b){var d=
this.c.A("Transform"),e=new f;e.save();this.ba();null!=d&&(b.aa(d),e.v(this.R(b)));b=this.sa("Opacity",1);1>b&&e.v(this.cb(b));d=this.u("StartPoint").split(",");b=parseFloat(d[0]);d=parseFloat(d[1]);var m=this.u("EndPoint").split(",");b={type:trn.b.Me,x0:b,y0:d,x1:parseFloat(m[0]),y1:parseFloat(m[1]),stops:this.kd()};e.I(a,[b]);e.v(c);e.restore();this.ra();return e},cf:function(a,c,b){var d=this.c.A("Transform"),e=new f,m=this.u("RadiusX"),k=this.u("RadiusY"),g=this.u("GradientOrigin"),h=this.u("Center");
e.save();this.ba();var n=parseFloat(m),p=parseFloat(k);trn.b.D(0<n&&0<p,"Invalid radius value");var q=h.split(",");h=parseFloat(q[0]);q=parseFloat(q[1]);var l=g.split(",");g=parseFloat(l[0]);l=parseFloat(l[1]);if(null!=d||m!==k)null!=d&&b.aa(d),d=p/n,l/=d,q/=d,k=new trn.H,k.vb(1,0,0,d,0,0),b.Qa(k),e.v(this.R(b));b=this.sa("Opacity",1);1>b&&e.v(this.cb(b));m={type:trn.b.Pe,x0:g,y0:l,x1:h,y1:q,r:m,stops:this.kd()};e.I(a,[m]);e.v(c);e.restore();this.ra();return e},uf:function(){trn.b.D(!this.Xb,"Incorrect custom glyph start");
this.o.push(trn.b.ze);this.s.push(null);this.Xb=!0},We:function(){trn.b.D(this.Xb,"Incorrect custom glyph end");this.o.push(trn.b.Ae);this.s.push(null);this.Xb=!1},v:f.prototype.v,I:f.prototype.I,Gd:function(a,c){var b=this.N.Z();a.Ja(b.ob)?c?this.v(c):this.I(trn.b.Ob,null):(a.o[0]===trn.b.Ca&&(b.ob=a),this.v(a))},Ec:function(a,c){var b=this.N.Z();a.Ja(b.ib)?this.v(c):(a.o[0]===trn.b.oa&&(b.ib=a),this.v(a))},Bd:function(a){var c=this.N.Z();a!==c.zb&&(c.zb=a,this.I(trn.b.He,[a]))},cb:function(a){var c=
this.N.Z();c.Ua*=a;return new f(trn.b.Ge,[c.Ua])},Cd:function(a){var c=this.N.Z();a!==c.hb&&(c.hb=a)},Fc:function(a){var c=this.N.Z();a!==c.mb&&(c.mb=a,this.o.push(trn.b.Le),this.s.push([a,this.fb().Xa()]))},Dd:function(a){var c=this.N.Z();a!==c.kb&&(c.kb=a,this.o.push(trn.b.Je),this.s.push([a]))},Ed:function(a){var c=this.N.Z();a!==c.lb&&(c.lb=a,this.o.push(trn.b.Ke),this.s.push([a]))},Fd:function(a){var c=this.N.Z();a!==c.nb&&(c.nb=a,this.o.push(trn.b.Ne),this.s.push([a]))},tf:function(a){var c=
this.N.Z();a!==c.jb&&(c.jb=a,this.o.push(trn.b.Fe),this.s.push([a]))},R:function(a){this.N.Z().za.Qa(a);return new f(trn.b.Pb,a.Rb())},fb:function(){return this.N.Z().za},Xe:function(){return this.N.Z().ta},gf:function(a){this.N.Z().ta.pb(a)},ba:function(a){a=a?this.N.Z().Jf():this.N.Z().clone();this.N.push(a);this.ia.add({})},ra:function(){this.N.pop();for(var a=Object.keys(this.ia[this.ia.length-1]),c=0;c<a;++c)this.I(trn.b.Be);this.ia.Jc(this.ia.length-1)},Ze:function(a,c,b){var d=new f,e=this.c.A("Transform");
d.save();this.ba();var m=this.u("Viewbox"),k=new trn.ga;k.Za(m);m=this.u("Viewport");var g=new trn.ga;g.Za(m);if(null!=e||k!==g){m=g.C/k.C;var h=g.B/k.B,n=g.l-k.l*m;k=g.m-k.m*h;null!=e&&b.aa(e);e=new trn.H;e.vb(m,0,0,h,n,k);b.Qa(e);d.v(this.R(b))}b=this.sa("Opacity",1);1>b&&d.v(this.cb(b));b=this.xa("TileMode","None");e=this.u("ImageSource");this.xb[e]=null;d.I(a,[{type:trn.b.Ie,name:"i"+this.Gc+"-"+parseInt(e.split("/")[2]),tm:"None"===b?"no-repeat":"repeat"}]);d.v(c);d.restore();this.ra();return d},
$e:function(){var a=new f,c=this.c.A("Transform");a.save();this.ba();var b=this.u("Viewbox"),d=new trn.ga;d.Za(b);b=this.u("Viewport");var e=new trn.ga;e.Za(b);if(null!=c||d!==e){b=e.C/d.C;var m=e.B/d.B,k=e.l-d.l*b;d=e.m-d.m*m;e=new trn.H;null!=c&&e.aa(c);c=new trn.H;c.vb(b,0,0,m,k,d);e.Qa(c);a.v(this.R(e))}c=this.sa("Opacity",1);1>c&&a.v(this.cb(c));this.xa("TileMode","None");c=this.u("ImageSource");this.xb[c]=null;c="i"+this.Gc+"-"+parseInt(c.split("/")[2]);this.od?a.I(trn.b.$c,[c,this.fb().Xa()]):
a.I(trn.b.$c,[c]);a.restore();this.ra();return a},qf:function(a){if(null!=a){var c=new trn.H;c.aa(a);this.v(this.R(c))}},j:function(a){for(var c,b=c=a.K,d=a.ja,e=d[c];" "!==e&&","!==e;)++c,e=d[c];b=d.substring(b,c);++c;a.K=c;return parseFloat(b)},Da:function(a){var c=" ",b=new trn.Mb(a,0,null,0),d=new trn.ga,e=!0;d.initData(0,0,0,0);if(b.K<b.ja.length)for(;" "===b.ja.charAt(b.K);)b.K++;for(;b.K<a.length;){if("A"<=b.ja.charAt(b.K)&&"Z">=b.ja.charAt(b.K)||"a"<=b.ja.charAt(b.K)&&"z">=b.ja.charAt(b.K))c=
b.ja.charAt(b.K),b.K++;else switch("a">c&&("H"!==c&&(b.g=0),"V"!==c&&(b.f=0)),c){case "m":case "M":b.f+=this.j(b);b.g+=this.j(b);e?(d.initData(b.f,b.g,b.f,b.g),e=!1):d.ka(b.f,b.g);b.S=!1;break;case "l":case "L":b.f+=this.j(b);b.g+=this.j(b);d.ka(b.f,b.g);b.S=!1;break;case "c":case "C":var f=this.j(b)+b.f;var k=this.j(b)+b.g;d.ka(f,k);b.S=!0;b.pa=this.j(b)+b.f;b.qa=this.j(b)+b.g;d.ka(b.pa,b.qa);b.f+=this.j(b);b.g+=this.j(b);d.ka(b.f,b.g);break;case "q":case "Q":f=this.j(b)+b.f;k=this.j(b)+b.g;d.ka(f,
k);b.f+=this.j(b);b.g+=this.j(b);d.ka(b.f,b.g);b.S=!1;break;case "s":case "S":b.S||(b.pa=b.f,b.qa=b.g);f=2*b.f-b.pa;k=2*b.g-b.qa;d.ka(f,k);b.S=!0;b.pa=this.j(b)+b.f;b.qa=this.j(b)+b.g;d.ka(b.pa,b.qa);b.f+=this.j(b);b.g+=this.j(b);d.ka(b.f,b.g);break;case "h":case "H":b.f+=this.j(b);d.ka(b.f,b.g);b.S=!1;break;case "v":case "V":b.g+=this.j(b);d.ka(b.f,b.g);b.S=!1;break;default:this.j(b),b.S=!1}for(;" "===a.charAt(b.K);)++b.K}return d.Cf(this.fb())},sc:function(){var a=null;this.ba();var c=this.c.A("RenderTransform");
if(null!=c){var b=new trn.H;b.aa(c);this.R(b)}var d=this.c.A("Stroke"),e=this.sa("StrokeThickness",1);c=this.c.A("Clip");null!=c&&(a=this.Da(c));c=this.c.A("Data");if(!this.c.T()){for(this.c.G();this.c.advance();)if(b=this.c.L(),trn.b.i(b,"Path.Data")&&!this.c.T()){this.c.G();this.c.advance()&&(b=new trn.H,b.aa(this.u("Transform")),this.R(b),trn.b.D(trn.b.i(this.c.L(),"PathGeometry"),"Path.Data must contain PathGeometry"),c=this.u("Figures"));this.c.F();break}else trn.b.i(b,"Path.Clip")?(trn.b.D(!this.c.T(),
"Path.Clip: Must contain PathGeometry element"),this.c.G(),this.c.advance()&&(b=new trn.H,b.aa(this.u("Transform")),this.R(b),a=this.Da(this.u("Figures")),b=b.gb(),this.R(b)),this.c.F()):trn.b.i(b,"Path.Stroke")&&(d=!0);this.c.F()}null!=a?a.pb(this.Da(c)):a=this.Da(c);this.ra();d&&a.Rd(e);return a},wb:function(a,c,b){a.S=!1;if(null==a.ua)this.o.push(trn.b.bd),this.s.push([a.f,a.g]);else for(var d=a.ua.length,e=a.f-c,f=a.g-b,k=f/e,g=Math.sqrt(e*e+f*f);1E-10<g;){var h=a.ua[a.Wb%d]-a.yb,n=h>g;n&&(a.yb+=
g,h=g);if(e){var p=Math.sqrt(h*h/(1+k*k));0>e&&(p=-p);c+=p;b+=k*p}else b+=0<f?h:-h;this.o.push(a.Wb%2?trn.b.dd:trn.b.bd);this.s.push([c,b]);g-=h;n||(++a.Wb,a.yb=0)}},Zc:function(a,c,b,d,e){a.S=!0;if(null==a.ua)this.o.push(trn.b.we),this.s.push([d,e,a.pa,a.qa,a.f,a.g]);else{var f=this.fb().Xa();f*=(Math.abs(a.f-c)+Math.abs(a.g-b))/5;var k=a.f,g=a.g;a.f=c;a.g=b;f=1/parseInt(f);for(var h=0;1>=h;h+=f){var n=1-h,p=a.f,q=a.g;a.f=n*n*n*c+3*n*n*h*d+3*n*h*h*a.pa+h*h*h*k;a.g=n*n*n*b+3*n*n*h*e+3*n*h*h*a.qa+
h*h*h*g;this.wb(a,p,q)}}},se:function(a){if(null==a.ua)this.o.push(trn.b.ye),this.s.push(null);else{var c=a.f,b=a.g;a.f=a.qd;a.g=a.rd;this.wb(a,c,b)}},kf:function(a){a.qd=a.f;a.rd=a.g;this.o.push(trn.b.dd);this.s.push([a.f,a.g]);a.S=!1;a.Wb=a.yc;a.yb=a.Ha},pf:function(a,c){var b=a.f,d=a.g;"a">c&&("H"!==c&&(a.g=0),"V"!==c&&(a.f=0));switch(c){case "m":case "M":a.f+=this.j(a);a.g+=this.j(a);this.kf(a);break;case "l":case "L":a.f+=this.j(a);a.g+=this.j(a);this.wb(a,b,d);break;case "c":case "C":c=this.j(a)+
a.f;var e=this.j(a)+a.g;a.pa=this.j(a)+a.f;a.qa=this.j(a)+a.g;a.f+=this.j(a);a.g+=this.j(a);this.Zc(a,b,d,c,e);break;case "q":case "Q":c=this.j(a)+a.f;e=this.j(a)+a.g;a.f+=this.j(a);a.g+=this.j(a);this.I(trn.b.Oe,[c,e,a.f,a.g]);a.S=!1;break;case "s":case "S":a.S||(a.pa=a.f,a.qa=a.g);c=2*a.f-a.pa;e=2*a.g-a.qa;a.S=!0;a.pa=this.j(a)+a.f;a.qa=this.j(a)+a.g;a.f+=this.j(a);a.g+=this.j(a);this.Zc(a,b,d,c,e);break;case "h":case "H":a.f+=this.j(a);this.wb(a,b,d);a.S=!1;break;case "v":case "V":a.g+=this.j(a);
this.wb(a,b,d);a.S=!1;break;default:this.j(a),a.S=!1}},ld:function(a){if("Flat"===a)return"butt";if("Square"===a)return"square";if("Round"===a||"Triangle"===a)return"round";trn.b.D(!1,"Invalid line cap "+a);return""},yd:function(a){this.zd(a,null,0)},zd:function(a,c,b){var d=" ";c=new trn.Mb(a,0,c,b);b=c.ja.charAt(c.K);this.o.push(trn.b.ve);this.s.push(null);if(c.K<c.ja.length)for(;" "===b;)c.K++,b=c.ja.charAt(c.K);for(;c.K<a.length;)for("A"<=b&&"Z">=b||"a"<=b&&"z">=b?(d=b,"z"!==b&&"Z"!==b||this.se(c),
c.K++):this.pf(c,d),b=c.ja.charAt(c.K);" "===b;)++c.K,b=c.ja.charAt(c.K)},save:f.prototype.save,restore:f.prototype.restore,rf:function(){var a=this.xa("trn:BlendMode","source-over");a=this.ha?"source-over":a;var c="source-over"!=a&&!this.Tb,b=this.c.A("Data"),d=!0;b&&"F"===b[0]&&(d=!1);var e=new f(trn.b.Nb,d?["evenodd"]:null),m=!1,k=this.Dc(),g=null,h=this.c.A("Fill");null!=h&&(g=this.Sb(h)?this.Ea(h,trn.b.oa,e):this.ub(h,trn.b.oa,e));this.Tb&&this.Bd(a);var n=h=null,p=this.sa("StrokeThickness",
1),q=this.c.A("Stroke");null!=q&&(this.Fc(p),h=this.Sb(q)?this.Ea(q,trn.b.Ca,new f(trn.b.Ob)):this.ub(q,trn.b.Ca,new f(trn.b.Ob)));q=null;var l=this.c.A("OpacityMask");null!=l&&(console.warn("Uh oh OpacityMask Resource!"),q=this.Ea(l));l=null;if(!this.c.T()){for(this.c.G();this.c.advance();){var r=this.c.L();trn.b.i(r,"Path.Clip")?(trn.b.D(!this.c.T(),"Path.Clip: Must contain PathGeometry element"),this.c.G(),this.c.advance()&&(k||(k=!0,this.save(),this.ba()),l=new trn.H,l.aa(this.u("Transform")),
this.v(this.R(l)),trn.b.D(trn.b.i(this.c.L(),"PathGeometry"),"Path.Clip must contain PathGeometry"),r=this.u("Figures"),this.ac(r),l=l.gb()),this.c.F()):trn.b.i(r,"Path.Data")&&!this.c.T()?(this.c.G(),this.c.advance()&&(b=new trn.H,b.aa(this.u("Transform")),null!=l?l.Qa(b):l=b,this.v(this.R(l)),trn.b.D(trn.b.i(this.c.L(),"PathGeometry"),"Path.Data must contain PathGeometry"),b=this.u("Figures")),this.c.F()):trn.b.i(r,"Path.Fill")?(this.c.G(),this.c.advance(),null!=q||c||"ImageBrush"!==this.c.L()?
g=this.eb(trn.b.oa,e):(m=!0,this.v(this.$e())),this.c.F()):trn.b.i(r,"Path.OpacityMask")?this.ha||(this.c.G(),this.c.advance(),q=this.eb(trn.b.oa,e),this.c.F()):trn.b.i(r,"Path.Stroke")&&(this.c.G(),this.c.advance(),h=this.eb(trn.b.Ca,new f(trn.b.Ob),p),this.c.F())}this.c.F()}if(null==q&&!c&&!m){trn.b.D(null!=b,"Paths must have Data defined");m=this.c.A("StrokeDashArray");if(null!=m)for(m=m.split(" "),n=Array(m.length),l=0;l<m.length;++l)if(n[l]=parseFloat(m[l])*p,!n[l]||.02>n[l])n[l]=.02;this.Cd(d?
"evenodd":"nonzero");d=this.sa("StrokeDashOffset",0);null!=n&&null!=g&&(this.yd(b),null!=g&&this.Ec(g,e),g=null);this.zd(b,n,d);null!=g&&this.Ec(g,e);null!=h&&(this.Dd(this.ld(this.xa("StrokeStartLineCap","Flat"))),this.Ed(this.xa("StrokeLineJoin","miter").toLowerCase()),this.Fd(this.sa("StrokeMiterLimit",10)),this.Gd(h))}k&&(this.restore(),this.ra());if(null!=q||c)this.ha=!0,this.pc(q,a);this.ha=!1},jd:function(a){var c=1,b=[255,255,255,255];if("#"===a.charAt(0)){if(7===a.length)return a;trn.b.D(9===
a.length,"Color "+a+" is invalid in a XOD file");c=a.substr(1,2);var d=a.substr(3,2);var e=a.substr(5,2);a=a.substr(7,2);c=parseInt(c,16)/255;b[0]=parseInt(d,16);b[1]=parseInt(e,16);b[2]=parseInt(a,16)}else"s"===a.charAt(0)?(d=a.split("#")[1].split(","),3<d.length?(c=parseFloat(d[0]),e=255*parseFloat(d[1]),b[0]=parseInt(0>e?0:255<e?255:e),e=255*parseFloat(d[2]),b[1]=parseInt(0>e?0:255<e?255:e),e=255*parseFloat(d[3])):(e=255*parseFloat(d[0]),b[0]=parseInt(0>e?0:255<e?255:e),e=255*parseFloat(d[1]),
b[1]=parseInt(0>e?0:255<e?255:e),e=255*parseFloat(d[2])),b[2]=parseInt(0>e?0:255<e?255:e)):trn.b.D(!1,"Invalid color for a XOD file");return"rgba("+b[0]+","+b[1]+","+b[2]+","+trn.b.Md(c)+")"},df:function(a,c){return this.ub(this.u("Color"),a,c)},ub:function(a,c,b){a=new f(c,this.jd(a));a.v(b);return a},uc:function(){var a=this.Va,c=this.o,b=this.s;this.o=[];this.s=[];this.Va=this.c.depth;this.ba(!0);if(!this.c.T()||!trn.b.i(this.c.L(),"Canvas"))for(this.Sa=!1;this.Ac(););this.ra();var d={operators:this.o,
data:this.s};this.Va=a;this.o=c;this.s=b;return d},md:function(a,c,b,d){var e=new f,m=this.u("Viewbox"),k=new trn.ga;k.Za(m);m=this.u("Viewport");var g=new trn.ga;g.Za(m);m=this.c.A("Transform");e.save();this.ba();if(!this.c.T()){for(this.c.G();this.c.advance();){var h=this.c.L();if(trn.b.i(h,"VisualBrush.Visual")){this.c.G();trn.b.D(this.c.advance(),"VisualBrush.Visual must contain Canvas, Path or Glyphs element");this.ba(!0);this.N.Z().za=new trn.H;var n=this.Qb();this.ra();this.c.F()}}this.c.F()}if("undefined"!==
typeof n&&0!==n.B&&0!==n.C){h=g.l-k.l;var p=g.m-k.m;k.pb(n);g=k;g.l+=h;g.m+=p}if(0===k.C||0===k.B)return e=new f(a,"rgba(0,0,0,0)"),e.v(c),e;if(null!=m||k!==g)h=g.C/k.C,n=g.B/k.B,p=g.l-k.l*h,g=g.m-k.m*n,null!=m&&b.aa(m),m=new trn.H,m.vb(h,0,0,n,p,g),b.Qa(m),e.v(this.R(b));g=this.fb().Xa();m=Math.min(k.C,k.B);h=this.sa("Opacity",1);1>h&&e.v(this.cb(h));n=this.xa("TileMode","None");p={};h=this.c.A("Visual");null!=h&&(h=this.Ea(h),p.operators={operators:h.o,data:h.s});if(!this.c.T()){for(this.c.G();this.c.advance();)h=
this.c.L(),trn.b.i(h,"VisualBrush.Visual")&&(this.c.G(),trn.b.D(this.c.advance(),"VisualBrush.Visual must contain Canvas, Path or Glyphs element"),p.operators=this.uc(),this.c.F());this.c.F()}p.type=trn.b.Ue;p.tm="None"===n?"no-repeat":"repeat";a===trn.b.Ca&&(p.strokeAdjust=d/b.Xa());if(k.l||k.m)p.x=k.l,p.y=k.m;p.w=k.C;p.h=k.B;p.minwh=m;p.scale=g;e.I(a,[p]);e.v(c);e.restore();this.ra();return e},Sb:function(a){return"{"===a.charAt(0)},Ea:function(a){var c=a.indexOf("StaticResource");trn.b.D(0<c,"Invalid resource reference: "+
a);c+=15;a=a.substr(c,a.length-1-c);c=null;for(var b=this.ia.length-1;0<=b;--b)if(Object.Td(this.ia[b],a)){c=this.ia[b][a];break}trn.b.D(null!=c,"Dictionary key "+a+" does not exist.");return new f(trn.b.Qe,[a])},Ac:function(){if(this.Sa){if(this.c.depth===this.Va)return trn.b.i(this.c.L(),"Canvas")&&this.Cb(),!1;var a=this.c.advance();if(!a){this.c.F();if(this.Ub.Z()===this.c.depth)return this.Ub.pop(),this.We(),!0;if(this.c.depth===this.Va)return trn.b.i(this.c.L(),"Canvas")&&this.Cb(),!1;this.Cb();
return!0}}this.Sa=!0;a=this.c.L();trn.b.i(a,"Canvas")?this.nf():trn.b.i(a,"Path")?this.rf():trn.b.i(a,"Glyphs")?this.xd(!1):trn.b.i(a,"trn:Glyphs")&&(this.c.T()||this.Ub.push(this.c.depth),this.xd(!0),this.c.T()||(this.c.G(),this.uf()));return!0},qe:function(){var a=trn.b.oa,c=new f(trn.b.Nb);a=this.md(a,c,new trn.H);c=this.Pd();this.ia[this.ia.length-1][c]=a;this.I(trn.b.ed,[c,a.o,a.s])},pe:function(a){a=this.uc();var c=this.Pd();this.ia[this.ia.length-1][c]=a;this.I(trn.b.ed,[c,a.operators,a.data])},
eb:function(a,c,b){var d=new trn.H,e=this.c.L();if(trn.b.i(e,"VisualBrush"))var f=this.md(a,c,d,b);else trn.b.i(e,"ImageBrush")?f=this.Ze(a,c,d):trn.b.i(e,"LinearGradientBrush")?f=this.af(a,c,d):trn.b.i(e,"RadialGradientBrush")?f=this.cf(a,c,d):trn.b.i(e,"SolidColorBrush")?f=this.df(a,c):trn.b.D(!1,"Invalid Brush Type: "+e),"undefined"!==typeof b&&(this.R(d),this.Fc(b/d.Xa()),this.R(d.gb()));return f},Ad:function(){var a=this.c.L();if(trn.b.i(a,"ResourceDictionary")&&!this.c.T()){for(this.c.G();this.c.advance();)a=
this.c.L(),trn.b.i(a,"VisualBrush")?this.qe():trn.b.i(a,"Canvas")?this.pe():trn.b.D(!1,"Resource type is invalid: "+a);this.c.F()}},Ye:function(){for(var a="";!this.done;)a+=this.qb();return a},qb:function(){this.ud=!1;for(this.xb={};this.o.length<this.pd&&!this.ud&&this.Ac(););this.Ac()||(this.done=!0);var a={operators:this.o,data:this.s};this.o=[];this.s=[];return a},zf:function(){var a=[],c=this.xb,b;for(b in c)a.add(b.substr(1));return a},done:!1,Sa:!1,ha:!1,td:0,sd:0,od:!1,pd:0,Ta:null,xb:null,
Va:0,ia:null,N:null,c:null,Ub:null,Xb:!1};trn.Fa=function(){this.zc=this.Ab=!1;this.Vb=this.xc=1;this.wc=this.Zb=this.$b=this.Yb=0};trn.Fa.prototype={Ab:!1,zc:!1,Vb:0,xc:0,Yb:0,wc:0,Zb:0,$b:0};trn.Ra=function(){};trn.Ra.Df=function(a,c){var b=new trn.Ra;b.ob="black";b.ib="black";b.hb="nonzero";b.Ua=1;b.zb="source-over";b.mb=1;b.kb="butt";b.lb="miter";b.nb=10;b.jb="10px sans-serif";b.za=new trn.H;b.ta=new trn.ga;b.ta.initData(0,0,a,c);return b};trn.Ra.prototype={clone:function(){var a=new trn.Ra;a.ob=
this.ob;a.ib=this.ib;a.hb=this.hb;a.Ua=this.Ua;a.zb=this.zb;a.mb=this.mb;a.kb=this.kb;a.lb=this.lb;a.nb=this.nb;a.jb=this.jb;a.za=new trn.H;a.za.vc(this.za);a.ta=new trn.ga;a.ta.initData(this.ta.l,this.ta.m,this.ta.C,this.ta.B);return a},Jf:function(){var a=new trn.Ra;a.ob="black";a.ib="black";a.hb="nonzero";a.Ua=1;a.zb="source-over";a.mb=1;a.kb="butt";a.lb="miter";a.nb=10;a.jb="10px sans-serif";a.za=new trn.H;a.za.vc(this.za);a.ta=new trn.ga;return a},ob:null,ib:null,hb:null,Ua:0,mb:0,kb:null,lb:null,
nb:0,jb:null,za:null,ta:null};trn.bb=function(a,c){this.x=a;this.y=c};trn.bb.prototype={x:0,y:0};trn.ga=function(){this.m=this.l=-1E6;this.C=this.B=2E6};trn.ga.prototype={initData:function(a,c,b,d){this.l=a;this.m=c;this.C=b;this.B=d},Hf:function(){return 0<this.C&&0<this.B},Za:function(a){a=a.split(",");trn.b.D(4===a.length,"Rectangles should contain 4 numbers");this.l=parseFloat(a[0]);this.m=parseFloat(a[1]);this.C=parseFloat(a[2]);this.B=parseFloat(a[3])},Cf:function(a){if(a.nd())return this;var c=
new trn.bb(this.l,this.m),b=new trn.bb(this.l,this.m+this.B),d=new trn.bb(this.l+this.C,this.m),e=new trn.bb(this.l+this.C,this.m+this.B);a.ec(c);a.ec(b);a.ec(d);a.ec(e);a=Math.min(c.x,b.x,d.x,e.x);var f=Math.min(c.y,b.y,d.y,e.y),k=new trn.ga;k.initData(a,f,Math.max(c.x,b.x,d.x,e.x)-a,Math.max(c.y,b.y,d.y,e.y)-f);return k},ka:function(a,c){a<this.l?(this.C+=this.l-a,this.l=a):a>this.l+this.C&&(this.C=a-this.l);c<this.m?(this.B+=this.m-c,this.m=c):c>this.m+this.B&&(this.B=c-this.m)},Lc:function(a){this.ka(a.l,
a.m);this.ka(a.l+a.C,a.m+a.B)},pb:function(a){var c=this.l;var b=this.l+this.C;var d=this.m;var e=this.m+this.B;var f=a.l;var k=a.l+a.C;var g=a.m;a=a.m+a.B;b<f||k<c||e<g||a<d?this.l=this.C=this.m=this.B=0:(this.l=c<f?f:c,this.C=(b<k?b:k)-this.l,this.m=d<g?g:d,this.B=(e<a?e:a)-this.m,this.C&&this.B||(this.l=this.C=this.m=this.B=0))},Rd:function(a){this.l-=a;this.m-=a;this.C+=2*a;this.B+=2*a},l:0,m:0,C:0,B:0};trn.H=function(){};trn.H.prototype={V:1,W:0,X:0,Y:1,da:0,ea:0,aa:function(a){var c=[1,0,0,
1,0,0];a=a.split(",");for(var b=0;b<a.length&&6>b;++b)c[b]=parseFloat(a[b]);this.V=c[0];this.W=c[1];this.X=c[2];this.Y=c[3];this.da=c[4];this.ea=c[5]},vb:function(a,c,b,d,e,f){this.V=a;this.W=c;this.X=b;this.Y=d;this.da=e;this.ea=f},vc:function(a){this.V=a.V;this.W=a.W;this.X=a.X;this.Y=a.Y;this.da=a.da;this.ea=a.ea},Qa:function(a){var c=this.V,b=this.W,d=this.X,e=this.Y;this.V=a.V*c+a.W*d;this.W=a.V*b+a.W*e;this.X=a.X*c+a.Y*d;this.Y=a.X*b+a.Y*e;this.da=a.da*c+a.ea*d+this.da;this.ea=a.da*b+a.ea*e+
this.ea},gb:function(){var a=new trn.H,c=this.V*this.Y-this.W*this.X;if(!c)return a;a.V=this.Y/c;a.X=-this.X/c;a.da=(this.X*this.ea-this.da*this.Y)/c;a.W=-this.W/c;a.Y=this.V/c;a.ea=-(this.V*this.ea-this.da*this.W)/c;return a},ec:function(a){var c=a.x*this.W+a.y*this.Y+this.ea;a.x=a.x*this.V+a.y*this.X+this.da;a.y=c},Xa:function(){var a=.707106781*this.V+.707106781*this.W,c=.707106781*this.X+.707106781*this.Y;return Math.sqrt(a*a+c*c)},nd:function(){return 1!==this.V||this.W||this.X||1!==this.Y||
this.da||this.ea?!1:!0},Rb:function(){return this.bf()},bf:function(){return this.nd()?null:[this.V,this.W,this.X,this.Y,this.da,this.ea]}};trn.Mb=function(a,c,b,d){this.ja=a;this.K=c;this.f=this.g=0;this.S=!1;this.ua=b;if(null!=this.ua){for(c=a=0;c<this.ua.length;++c)a+=this.ua[c];this.Ha=d%a;0>this.Ha&&(this.Ha+=a);for(c=this.yc=0;this.Ha>this.ua[c];++c)this.Ha-=this.ua[c],++this.yc}};trn.Mb.prototype={ja:null,K:0,ua:null,Wb:0,yb:0,yc:0,Ha:0,f:0,g:0,qd:0,rd:0,S:!1,pa:0,qa:0};trn.wd=function(){};
trn.wd.prototype={};trn.b.ca("trn.Converter");trn.Fa.ca("trn._index");trn.Ra.ca("trn._gState");trn.bb.ca("trn.Point");trn.ga.ca("trn._rect");trn.H.ca("trn._matrix2D");trn.Mb.ca("trn._abbrGeomItr");trn.wd.ca("trn._pageInfo");trn.b.mg="http://schemas.microsoft.com/xps/2005/06/resourcedictionary-key";trn.b.sg="http://schemas.openxps.org/oxps/v1.0/resourcedictionary-key";trn.b.yg="http://schemas.microsoft.com/winfx/2006/xaml";trn.b.vf="http://schemas.microsoft.com/xps/2005/06";trn.b.zg="http://schemas.microsoft.com/winfx/2006/xaml/presentation";
trn.b.tg="http://schemas.openxps.org/oxps/v1.0";trn.b.Bg="http://schemas.microsoft.com/xps/2005/06/documentstructure";trn.b.rg="http://schemas.openxps.org/oxps/v1.0/documentstructure";trn.b.wg="http://schemas.openxmlformats.org/package/2006/relationships";trn.b.dg="http://schemas.openxmlformats.org/package/2006/content-types";trn.b.ng="http://schemas.openxmlformats.org/markup-compatibility/2006";trn.b.eg="http://schemas.openxmlformats.org/package/2006/metadata/core-properties";trn.b.fg="http://purl.org/dc/elements/1.1/";
trn.b.gg="http://purl.org/dc/terms/";trn.b.Ag="http://www.w3.org/XML/1998/namespace";trn.b.xg="clr-namespace:PDFTron.SilverDox.Internal;assembly=SilverDox";trn.b.Cg="http://schemas.microsoft.com/xps/2005/06/restricted-font";trn.b.ug="http://schemas.openxps.org/oxps/v1.0/restricted-font";trn.b.og="application/vnd.ms-package.obfuscated-opentype";trn.b.vg="http://www.pdftron.com/silverdox/2010/09";trn.b.Se=0;trn.b.Re=1;trn.b.Pb=2;trn.b.kg=3;trn.b.Le=4;trn.b.Je=5;trn.b.Ca=6;trn.b.oa=7;trn.b.Ge=8;trn.b.ed=
9;trn.b.Be=10;trn.b.ue=11;trn.b.Qe=12;trn.b.ve=13;trn.b.ye=14;trn.b.Nb=15;trn.b.Ob=16;trn.b.xe=17;trn.b.dd=18;trn.b.bd=19;trn.b.Oe=20;trn.b.we=21;trn.b.Fe=22;trn.b.Ce=23;trn.b.cd=24;trn.b.Te=25;trn.b.Ne=26;trn.b.Ke=27;trn.b.$c=28;trn.b.jg=29;trn.b.ig=30;trn.b.Ee=31;trn.b.ze=32;trn.b.Ae=33;trn.b.He=34;trn.b.fd=35;trn.b.Ve=36;trn.b.hg=37;trn.b.ad=38;trn.b.De=39;trn.b.qc=40;trn.b.Ue=1;trn.b.Me=2;trn.b.Pe=3;trn.b.Ie=4;trn.b.pg="S r t T w c s f a L R P A b z F X C M l q B n x m W i j I Z d D e xw cgb cge g bO tm".split(" ");
trn.b.qg="S r t T w c s f a L R P A b z F X C M l q B n xc m W i j I Z d D e xcw cgb cge g bO tm".split(" ")})()},function(f,a,c){var b=c(0);(function(a){function c(a){this.J="";this.Qf=new b.a.lc(a);this.Ic();this.start=0}a.trn.b||(a.trn=trn);c.prototype={Id:102400,mark:function(a){var b=a-this.start;b>c.prototype.Id&&(this.J=this.J.slice(b),this.start=a)},indexOf:function(a,b){b-=this.start;do var c=this.J.indexOf(a,b);while(-1===c&&this.Ic());return c+this.start},charAt:function(a){a-=this.start;
a>=this.J.length&&this.Ic();return this.J.charAt(a)},substring:function(a,b){a-=this.start;b-=this.start;return this.J.substring(a,b)},Ic:function(){var a=this.Qf.Od(c.prototype.Id);return a.length?(this.J+=a,!0):!1}};a.qb=function(){if(a.Wa.done)return a.postMessage({command:"done"}),a.Wa=null,!1;var b=a.Wa.qb();a.postMessage({command:"nextChunk",resources:a.Wa.zf(),dataString:b});return!0};var d=function(){var a=navigator.userAgent.toLowerCase();return(a=/(msie) ([\w.]+)/.exec(a)||/(trident)(?:.*? rv:([\w.]+)|)/.exec(a))?
parseInt(a[2],10):a}();a.Jd=function(){if(9===d)for(;a.qb(););else setTimeout(function(){a.Wa&&a.qb()&&a.Jd()},0)};a.ie=c;a.Hd=!1;a.onmessage=function(b){switch(b.data.command){case "data":var c=new a.le(new a.ie(b.data.dataString));a.Wa=new a.trn.b(c,a.Hd,a.Pf,b.data.docId);a.Kd&&a.Jd();break;case "nextChunk":a.Kd||a.Wa&&a.qb();break;case "cancel":a.Wa=null;a.postMessage({command:"done"});break;case "options":a.Hd=b.data.imageScaling;a.Pf=b.data.specialBlendSupported;a.Kd=b.data.continueWithoutPrompt;
break;default:throw Error("Unknown message command "+b.data.command);}}})(self)}]);}).call(this || window)
