(function(){'use strict';(window.webpackJsonp=window.webpackJsonp||[]).push([[3],{537:function(x,y,a){a.r(y);var w=a(0);a.n(w);var r=a(21),f=a(9),n=a(6),e=a(79);y["default"]=function(a){function b(a){var b=[];for(a.za();a.advance();){var e=a.Fa();"field"===e?b.push(String(a.V("name"))):console.warn("unrecognised field list element: "+e)}a.Na();return b}function x(a,b){return b?"false"===a?!1:!0:"true"===a?!0:!1}function y(a,e){var h=a.Fa();switch(h){case "javascript":return{name:"JavaScript",javascript:a.current.textContent};
case "uri":return{name:"URI",uri:a.V("uri")};case "goto":h=null;a.za();if(a.advance()){var n=a.V("fit");h={page:a.V("page"),fit:n};if("0"===h.page)console.warn("null page encountered in dest");else switch(e=e(Number(h.page)),n){case "Fit":case "FitB":break;case "FitH":case "FitBH":h.top=e.ha({x:0,y:a.V("top")||0}).y;break;case "FitV":case "FitBV":h.left=e.ha({x:a.V("left")||0,y:0}).x;break;case "FitR":n=e.ha({x:a.V("left")||0,y:a.V("top")||0});e=e.ha({x:a.V("right")||0,y:a.V("bottom")||0});e=new f.a(n.x,
n.y,e.x,e.y);h.top=e.aa;h.left=e.da;h.bottom=e.ba;h.right=e.ea;break;case "XYZ":n=e.ha({x:a.V("left")||0,y:a.V("top")||0});h.top=n.y;h.left=n.x;h.zoom=a.V("zoom")||0;break;default:console.warn("unknown dest fit: "+n)}h={name:"GoTo",dest:h}}else console.tZ("missing dest in GoTo action");a.Na();return h;case "submit-form":h={name:"SubmitForm",url:a.V("url"),format:a.V("format"),method:a.V("method")||"POST",exclude:x(a.V("exclude"),!1)};e=a.V("flags");h.flags=e?e.split(" "):[];for(a.za();a.advance();)switch(e=
a.Fa(),e){case "fields":h.fields=b(a);break;default:console.warn("unrecognised submit-form child: "+e)}a.Na();return h;case "reset-form":h={name:"ResetForm",exclude:x(a.V("exclude"),!1)};for(a.za();a.advance();)switch(e=a.Fa(),e){case "fields":h.fields=b(a);break;default:console.warn("unrecognised reset-form child: "+e)}a.Na();return h;case "hide":h={name:"Hide",hide:x(a.V("hide"),!0)};for(a.za();a.advance();)switch(e=a.Fa(),e){case "fields":h.fields=b(a);break;default:console.warn("unrecognised hide child: "+
e)}a.Na();return h;case "named":return{name:"Named",action:a.V("name")};default:console.warn("Encountered unexpected action type: "+h)}return null}function id(a,b,e){var f={};for(a.za();a.advance();){var h=a.Fa();switch(h){case "action":h=a.V("trigger");if(b?-1!==b.indexOf(h):1){f[h]=[];for(a.za();a.advance();){var n=y(a,e);Object(w.isNull)(n)||f[h].push(n)}a.Na()}else console.warn("encountered unexpected trigger on field: "+h);break;default:console.warn("encountered unknown action child: "+h)}}a.Na();
return f}function oe(a){return"calculation-order"===a.Fa()?b(a):[]}function z(a){return new n.a(a.V("r")||0,a.V("g")||0,a.V("b")||0,a.V("a")||1)}function ne(a,b){var e=a.V("name"),f=a.V("type")||"Type1",h=a.V("size"),n=b.ha({x:0,y:0});h=b.ha({x:Number(h),y:0});b=n.x-h.x;n=n.y-h.y;e={name:e,type:f,size:Math.sqrt(b*b+n*n)||0,strokeColor:[0,0,0],fillColor:[0,0,0]};for(a.za();a.advance();)switch(f=a.Fa(),f){case "stroke-color":e.strokeColor=z(a);break;case "fill-color":e.fillColor=z(a);break;default:console.warn("unrecognised font child: "+
f)}a.Na();return e}function le(a,b){var e={border:{style:"Solid",width:1},backgroundColor:[],fieldName:a.V("field"),page:a.V("page"),index:a.V("index")||0,rotation:a.V("rotation")||0,flags:[]},h=a.V("appearance");h&&(e.appearance=h);(h=a.V("flags"))&&(e.flags=h.split(" "));for(a.za();a.advance();)switch(h=a.Fa(),h){case "rect":var n=a,r=b(Number(e.page));h=r.ha({x:n.V("x1")||0,y:n.V("y1")||0});n=r.ha({x:n.V("x2")||0,y:n.V("y2")||0});h=new f.a(h.x,h.y,n.x,n.y);h.normalize();e.rect={x1:h.x1,y1:h.y1,
x2:h.x2,y2:h.y2};break;case "border":h=a;n={style:h.V("style")||"Solid",width:h.V("width")||1,color:[0,0,0]};for(h.za();h.advance();)switch(r=h.Fa(),r){case "color":n.color=z(h);break;default:console.warn("unrecognised border child: "+r)}h.Na();e.border=n;break;case "background-color":e.backgroundColor=z(a);break;case "actions":e.actions=id(a,"E X D U Fo Bl PO PC PV PI".split(" "),b);break;case "appearances":h=a;n=re.Bi(e,"appearances");for(h.za();h.advance();)if(r=h.Fa(),"appearance"===r){r=h.V("name");
var w=re.Bi(n,r);r=h;for(r.za();r.advance();){var x=r.Fa();switch(x){case "Normal":re.Bi(w,"Normal").data=r.current.textContent;break;default:console.warn("unexpected appearance state: ",x)}}r.Na()}else console.warn("unexpected appearances child: "+r);h.Na();break;case "extra":h=a;n=b;r={};for(h.za();h.advance();)switch(w=h.Fa(),w){case "font":r.font=ne(h,n(1));break;default:console.warn("unrecognised extra child: "+w)}h.Na();h=r;h.font&&(e.font=h.font);break;case "captions":n=a;h={};(r=n.V("Normal"))&&
(h.Normal=r);(r=n.V("Rollover"))&&(h.Rollover=r);(n=n.V("Down"))&&(h.Down=n);e.captions=h;break;default:console.warn("unrecognised widget child: "+h)}a.Na();return e}function me(a){var b={value:a.V("value")};(a=a.V("display-value"))&&(b.displayValue=a);return b}function pe(b,e){var f=b.V("name"),h={type:b.V("type"),quadding:b.V("quadding")||"Left-justified",maxLen:b.V("max-len")||-1},n=b.V("flags");Object(w.isString)(n)&&(h.flags=n.split(" "));for(b.za();b.advance();)switch(n=b.Fa(),n){case "actions":h.actions=
id(b,["C","F","K","V"],e);break;case "default-value":n=b;n.za();n.advance();var r=n.current.textContent;n.Na();h.defaultValue=r;break;case "font":h.font=ne(b,e);break;case "options":n=b;r=[];for(n.za();n.advance();){var x=n.Fa();switch(x){case "option":r.push(me(n));break;default:console.warn("unrecognised options child: "+x)}}n.Na();h.options=r;break;default:console.warn("unknown field child: "+n)}b.Na();return new a.Annotations.fa.oa(f,h)}function qe(a,b){switch(a.type){case "Tx":return new r.h(a,
b);case "Ch":return a.flags.get("Combo")?new r.c(a,b):new r.d(a,b);case "Btn":return a.flags.get("PushButton")?new r.e(a,b):a.flags.get("Radio")?new r.f(a,b):new r.b(a,b);case "Sig":return new r.g(a,b);default:console.warn("Unrecognised field type: "+a.type)}return null}function se(a,b){var e={number:a.V("number")};for(a.za();a.advance();){var f=a.Fa();switch(f){case "actions":e.actions=id(a,["O","C"],b);break;default:console.warn("unrecognised page child: "+f)}}a.Na();return e}a.Af=a.Af||{};var re=
a.Af;re.dN={parse:function(a,b,f,h){var n=[],r={};a.za();var w=[],x={},y=[];Object(e.a)(function(){if(a.advance()){var e=a.Fa();switch(e){case "calculation-order":w=oe(a);break;case "document-actions":x=id(a,["Init","Open"],b);break;case "pages":e=[];for(a.za();a.advance();){var f=a.Fa();switch(f){case "page":e.push(se(a,b));break;default:console.warn("unrecognised page child: "+f)}}a.Na();y=e;break;case "field":e=pe(a,b(1));r[e.name]=e;break;case "widget":f=le(a,b);(e=r[f.fieldName])?(e=qe(e,f),
n.push(e)):console.warn("ignoring widget with no corresponding field data: "+f.fieldName);break;default:console.warn("Unknown element encountered in PDFInfo: "+e)}return!0}return!1},function(){a.Na();f({calculationOrder:w,widgets:n,fields:r,documentActions:x,pages:y,custom:[]})},h)},GV:pe,JV:le,EV:oe}}(window)}}]);}).call(this || window)
